import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'tr' | 'ka';

const translations = {
    en: {
        welcome: 'Welcome Back',
        login_subtitle: 'Log in to access your campus network.',
        email: 'Email',
        password: 'Password',
        forgot_password: 'Forgot password?',
        login: 'Log In',
        no_account: "Don't have an account? ",
        apply_access: 'Apply for access',
        create_account: 'Create Account',
        register_subtitle: 'Join your campus community and stay connected.',
        full_name: 'Full Name',
        already_account: 'Already have an account? ',
        login_now: 'Log in',
        home: 'Home',
        profile: 'Profile',
        notifications: 'Notifications',
        friends: 'Friends',
        settings: 'Settings',
        logout: 'Log out',
        delete_account: 'Delete account',
        posts: 'Posts',
        events: 'Events',
        polls: 'Polls',
        listings: 'Listings',
        search: 'Search',
        connect: 'Connect',
        message: 'Message',
        edit_profile: 'Edit Profile',
        share_profile: 'Share profile',
        complete_profile: 'Complete your profile to stand out!',
        bio_placeholder: 'Add a bio to tell students about yourself',
        campus_pioneer: 'Campus Pioneer Rank',
        loading: 'Loading...',
        feed: 'Feed',
        explore: 'Explore',
        marketplace: 'Marketplace',
        study: 'Study',
        create: 'Create',
        new_post: 'New Post',
        share_with_campus: 'Share with your campus',
        new_event: 'New Event',
        organize_activities: 'Organize campus activities',
        sell_request: 'Sell or Request Item',
        list_on_market: 'List on marketplace',
        ask_question: 'Ask Question',
        get_homework_help: 'Get homework help',
        community_hub: 'Community Hub',
        search_communities_placeholder: 'Search communities...',
        search_students_placeholder: 'Search by name or dept',
        communities_tab: 'Communities',
        students_tab: 'Students',
        members_count: 'members',
        friends_label: 'Friends',
        requested_label: 'Requested',
        add_friend_label: 'Add Friend',
        discover_communities: 'Discover & join communities',
        start_new_community: 'Start New Community',
        no_communities_yet: 'No communities yet',
        be_the_first: 'Be the first to start one!',
        no_students_found: 'No students found',
        try_different_search: 'Try a different search term',
        all_listings: 'All Listings',
        for_sale: 'For Sale',
        requests_tab: 'Requests',
        items_count: 'Items',
        all_communities: 'All Communities',
        filter_by_community: 'Filter by Community',
        request_badge: 'REQUEST',
        free_badge: 'FREE',
        new_badge: 'NEW',
        looking_for: 'is looking for',
        untitled_item: 'Untitled Item',
        no_requests_yet: 'No requests here yet',
        no_items_for_sale: 'No items for sale yet',
        nothing_here_yet: 'Nothing here yet',
        be_the_first_to_request: 'Be the first to request something!',
        be_the_first_to_list: 'Be the first to list something!',
        be_the_first_to_both: 'Be the first to list or request something!',
        request_an_item: 'Request an Item',
        sell_an_item: 'Sell an Item',
        create_a_listing: 'Create a Listing',
        all_subjects: 'All',
        no_questions_in: 'No questions in',
        be_the_first_to_ask: 'Be the first to ask or help out!',
        search_messages_placeholder: 'Search messages...',
        no_conversations: 'No conversations',
        start_chatting_sub: 'Start chatting with community members',
        profile_not_found: 'User profile not found',
        user_blocked: 'User Blocked',
        profile_unavailable: 'Profile Unavailable',
        block_desc_me: 'You have blocked this user. Unblock them to interact.',
        block_desc_other: 'You cannot view this user content.',
        unblock_label: 'Unblock',
        connect_label: 'Connect',
        message_label: 'Message',
        share_profile_label: 'Share Profile',
        no_content_yet: 'No content here yet',
        campus_rank_label: 'Campus Pioneer Rank',
        score_label: 'Score',
        uniscore_label: 'UniScore',
        uniscore_title: 'What is UniScore?',
        uniscore_body: 'UniScore reflects your positive contribution on UniConn. It grows as you post, help others, and engage respectfully in your campus community.',
        share_profile_title: "Check out {{name}}'s profile on Uni!",
        share_profile_message: "Check out {{name}}'s student profile on Uni Hub: {{url}}",
        request_cancelled_title: 'Request Cancelled',
        request_cancelled_message: 'Your connection request has been withdrawn.',
        friend_removed_title: 'Friend Removed',
        friend_removed_message: 'You are no longer friends with {{name}}.',
        connection_update_failed: 'Failed to update connection. Please try again.',
        manage_request_title: 'Manage Request',
        manage_friendship_title: 'Manage Friendship',
        cancel_sent_request: 'Cancel Sent Request',
        unfriend_student: 'Unfriend Student',
        connection_request_sent_body: 'Connection request sent successfully!',
        friends_only_title: 'Friends Only',
        friends_only_body: 'You can only message your friends. Send a connection request first!',
        profile_options_title: 'Profile Options',
        block_user_option: 'Block User',
        unblock_user_option: 'Unblock User',
        report_student_option: 'Report Student',
        spam_or_scam_option: 'Spam or Scam',
        impersonation_option: 'Impersonation',
        report_submitted_title: 'Report Submitted',
        report_submitted_message: 'Thank you for helping keep our community safe. Our team will review this report.',
        report_submit_failed: 'Failed to submit report. Please try again.',
        block_user_title: 'Block User',
        block_user_confirm: "Are you sure you want to block {{name}}? They won't be able to message you or see your content.",
        block_user_confirm_action: 'Block',
        unblock_user_title: 'Unblock User',
        unblock_user_confirm: 'Are you sure you want to unblock {{name}}?',
        user_blocked_message: '{{name}} has been blocked.',
        user_unblocked_title: 'User Unblocked',
        user_unblocked_message: '{{name}} has been unblocked.',
        block_user_failed: 'Could not block user. Try again.',
        unblock_user_failed: 'Could not unblock user. Try again.',
        uniscore_reputation_title: 'UniScore & Reputation',
        uniscore_reputation_message: 'UniScore reflects your campus impact. Earn points by sharing resources, organizing events, and engaging with peers.',
        campus_rank_self_body: 'Your Pioneer Rank represents your early adoption status at {{university}}. The lower the number, the earlier you joined the community. Because this is unique to your campus, you hold a permanent piece of history!',
        campus_rank_self_university_fallback: 'your university',
        campus_rank_other_body: "{{name}}'s Pioneer Rank represents their early adoption status at {{university}}. The lower the number, the earlier they joined the community. Because this is unique to their campus, they hold a permanent piece of history!",
        campus_rank_university_fallback: 'their university',
        post_tab: 'Posts',
        event_tab: 'Events',
        poll_tab: 'Polls',
        market_tab: 'Market',
        reply: 'Reply',
        replies: 'Replies',
        help_out: 'Help out',
        replying_to: 'Replying to',
        write_comment_placeholder: 'Write a comment…',
        new_message: 'New message',
        you_received_a_new_message: 'You received a new message',
        group_chat: 'Group chat',
        activity_header: 'Activity',
        all_caught_up_activity: 'All caught up',
        activity_empty_sub: 'We will notify you about important updates here',
        cancel_label: 'Cancel',
        cancel_request: 'Cancel Request',
        send_to_friends: 'Send to Friends',
        search_friends: 'Search friends…',
        sent: 'Sent',
        send: 'Send',
        no_friends_found: 'No friends found',
        no_messages_yet: 'No messages yet',
        you_shared_post: 'You shared this post',
        someone_shared_post: '{{name}} shared this post',
        video_label: 'Video',
        photo_label: 'Photo',
        user_fallback: 'User',
        group_fallback: 'Group',
        conversation_options: 'Conversation Options',
        clear_history: 'Clear History',
        private_label: 'PRIVATE',
        join_required_title: 'Join Required',
        join_required_body: 'You need to be a member to see this content.',
        request_sent_title: 'Request Sent',
        request_sent_body: 'An admin will review your request.',
        leave_community_title: 'Leave Community',
        leave_community_body: 'Are you sure you want to leave this community?',
        retract_request_title: 'Retract Request',
        retract_request_body: 'Are you sure you want to retract your join request?',
        members_only: 'Members Only',
        join_to_chat: 'Join to Chat',
        enter_chat_room: 'Enter Chat Room',
        post_something: 'Post Something',
        admin_creator: 'CREATOR ADMIN',
        students_label: 'Students',
        manage: 'Manage',
        locked_body: 'Join this community to see its feed and connect with students. Content is hidden to protect privacy.',
        math: 'Mathematics',
        science: 'Science',
        english: 'English',
        history: 'History',
        physics: 'Physics',
        cs: 'Comp Sci',
        business: 'Business',
        arts: 'Arts',
        other: 'Other',
        new_community_header: 'New Community',
        messages_header: 'Messages',
        chat_header: 'Chat',
        study_discussion_header: 'Study Discussion',
        ask_for_help_header: 'Ask for Help',
        schedule_event_header: 'Schedule Event',
        share_pov_header: 'Share Your POV',
        language: 'Language',
        lang_en: 'English',
        lang_tr: 'Turkish',
        lang_ka: 'Georgian',
        // Marketplace & categories
        books: 'Books',
        clothes: 'Clothes',
        accessories: 'Accessories',
        feed_tab: 'Feed',
        events_tab: 'Events',
        market_tab_label: 'Market',
        list_view: 'List',
        calendar_view: 'Calendar',
        community_not_found: 'Community not found',
        private_community_title: 'Private Community',
        private_community_body: 'Join this community to see its feed and connect with students. Content is hidden to protect privacy.',
        request_to_join: 'Request to Join',
        cancel_request: 'Cancel Request',
        empty_events: 'No upcoming events posted.',
        empty_market: 'The marketplace is empty.',
        empty_feed: 'Be the first to share something here!',
        enter_chat_room: 'Enter Chat Room',
        members_only: 'Members Only',
        join_to_chat: 'Join to Chat',
        post_something: 'Post Something',
        member_status_member: 'Member',
        member_status_pending: 'Requested',
        member_status_request: 'Request',
        member_status_join: 'Join Hub',
        admin_creator: 'CREATOR ADMIN',
        study_hub: 'STUDY HUB',
        private_label: 'PRIVATE',
        students_label: 'Students',
        manage: 'Manage',
        join_required_title: 'Join Required',
        join_required_body: 'You need to be a member to enter this chat.',
        chat_initializing_title: 'Chat Initializing',
        chat_initializing_body: 'The chat room is being synchronized. Please try again in a few seconds.',
        retract_request_title: 'Retract Request',
        retract_request_body: 'Are you sure you want to retract your join request for this community?',
        leave_community_title: 'Leave Community',
        leave_community_body: 'Are you sure you want to leave this community?',
        request_sent_title: 'Request Sent',
        request_sent_body: 'This community is private. An admin will review your request.',
        pulse_title: 'The Pulse',
        pulse_rules_title: 'Pulse Rules',
        pulse_rules_body: 'No bullying, no names, no harassment. Keep the campus safe.',
        pulse_empty_title: 'The Pulse is empty',
        pulse_empty_sub: 'Be the first to speak your mind anonymously.',
        pulse_empty_cta: 'Ignite The Pulse',
        pulse_guidelines_title: 'Pulse Community Guidelines',
        pulse_guidelines_body: 'No bullying, harassment, or naming individuals. Keep it real, but keep it respectful.',
        pulse_input_placeholder: "What's on your mind? Spill it anonymously...",
        pulse_create_cta: 'Confess',
        pulse_posting_as: 'Posting as',
        pulse_beta_notice: 'The Pulse is in beta. Features and behavior may change.',
        pulse_uploading_image: 'Uploading image...',
        pulse_failed_to_post: 'Failed to post confession',
        pulse_failed_to_edit: 'Failed to edit confession',
        pulse_delete_title: 'Delete Pulse',
        pulse_delete_confirm: 'This confession will be removed permanently.',
        pulse_delete_are_you_sure: 'Are you sure?',
        pulse_failed_to_delete: 'Failed to delete',
        pulse_share_prefix: 'Check out this anonymous confession on Uni Pulse:',
        pulse_link_copied: 'The confession link has been copied.',
        pulse_report_thanks: 'Thank you. We will review this confession.',
        pulse_options_title: 'Pulse Options',
        pulse_report_title: 'Report Confession',
        pulse_report_bullying: 'Bullying or Harassment',
        pulse_report_hate_speech: 'Hate Speech',
        pulse_anonymous_student: 'Anonymous Student',
        pulse_you_anonymous: 'You (anonymous)',
        pulse_anon_prefix: 'Anon #',
        pulse_replies_header: 'Anonymous Replies',
        pulse_reply_placeholder: 'Reply anonymously...',
        pulse_removed_message: 'This confession has been removed.',
        pulse_not_found_title: 'Not Found',
        pulse_comment_failed: 'Failed to post comment',
        // Edit profile
        save: 'Save',
        change_profile_picture: 'Change Profile Picture',
        display_name: 'Display Name',
        username_label: 'Username',
        personal_details: 'Personal Details (Optional)',
        hometown: 'Hometown',
        age: 'Age',
        relationship_status: 'Relationship Status',
        select_status: 'Select Status',
        show_hometown: 'Show Hometown',
        show_age: 'Show Age',
        show_relationship: 'Show Relationship',
        academic_details: 'Academic Details',
        department_label: 'Department / Major',
        select_department: 'Select Department',
        graduation_year_label: 'Graduation Year / Level',
        select_year: 'Select Year/Level',
        show_department: 'Show Department',
        show_year: 'Show Class/Year',
        show_rank: 'Show Pioneer Rank',
        success: 'Success',
        profile_updated: 'Profile updated successfully!',
        error: 'Error',
        name_required: 'Name is required',
        upload_failed: 'Upload Failed',
        clear: 'Clear',
        friend_requests: 'Friend Requests',
        new_friend_request: 'New Friend Request',
        friend_requests_count: '{{count}} Friend Requests',
        friend_request_banner_single: '{{name}} wants to connect',
        friend_request_banner_multiple: 'People want to connect with you',
        wants_to_be_your_friend: 'Wants to be your friend',
        no_pending_requests: 'No pending requests',
        friend_requests_empty_sub: "When students want to be your friend, they'll appear here.",
        accept: 'Accept',
        decline: 'Decline',
        view_all: 'View All',
        edit_label: 'Edit',
        delete_label: 'Delete',
        edited_label: 'edited',
        you_badge: 'you',
        post_header: 'Post',
        post_not_found: 'Post not found',
        no_replies_yet: 'No replies yet. Be the first.',
        failed_to_post_comment: 'Failed to post comment',
        delete_comment_title: 'Delete Comment',
        delete_comment_confirm: 'Are you sure you want to delete this comment?',
        failed_to_delete_comment: 'Failed to delete comment',
        willing_to_pay: 'Willing to pay',
        looking_for_label: 'Looking For',
        help_source: 'Help Source',
        view_item: 'View Item',
        anonymous_user: 'Anonymous',
        event_badge: 'EVENT',
        passed_label: 'PASSED',
        interested_label: 'Interested',
        person_label: 'person',
        people_label: 'people',
        event_details_header: 'Event Details',
        event_already_ended: 'This event has already ended.',
        loading_event: 'Loading event...',
        community_label: 'Community',
        person_is_interested: 'person is interested',
        people_are_interested: 'people are interested',
        about_this_event: 'About this event',
        no_event_description: 'No description provided.',
        im_interested_label: "I'm Interested",
        mark_as_interested: 'Mark as Interested',
        done_label: 'Done',
        marked_as_status: "You're marked as {{status}}!",
        poll_badge: 'POLL',
        votes_label: 'votes',
        tap_to_vote: 'Tap to vote',
        share_option: 'Share',
        copy_link_option: 'Copy Link',
        report_option: 'Report',
        edit_post_option: 'Edit Post',
        post_options_title: 'Post Options',
        poll_options_title: 'Poll Options',
        marketplace_listing_title: 'Marketplace Listing',
        why_reporting_title: 'Why are you reporting?',
        inappropriate_content_option: 'Inappropriate Content',
        harassment_option: 'Harassment',
        spam_option: 'Spam',
        scam_option: 'Scam',
        link_copied_title: 'Link Copied',
        post_link_copied: 'The post link has been copied to your clipboard.',
        listing_link_copied: 'The listing link has been copied to your clipboard.',
        poll_link_copied: 'The poll link has been copied to your clipboard.',
        notifications_label: 'Notifications',
        theme: 'Theme',
        select_theme: 'Select Theme',
        theme_light: 'Light',
        theme_dark: 'Dark',
        theme_system: 'System',
        privacy_policy: 'Privacy Policy',
        terms_of_use: 'Terms of Use',
        privacy_desc: 'How we protect your campus data',
        terms_desc: 'The rules of our student community',
        logout_label: 'Log out',
        delete_account_label: 'Delete account',
        no_items_yet: 'No items yet',
        score: 'Score',
        pulse_rules_prefix: 'Pulse Rules:',
        listed: 'Listed',
        study_question_not_found: 'Question not found',
        study_answers: 'Answers',
        study_empty_answers: 'Nobody has answered yet.',
        study_empty_answers_sub: 'Be the first to help out!',
        study_answer_placeholder: 'Type your answer or explanation...',
        study_post_answer_failed: 'Failed to post answer',
        you_tag: '(You)',
        market_listing_fallback: 'Listing...',
        market_item_not_found: 'Item not found',
        go_back: 'Go Back',
        market_share_text: 'Check out this {{title}} on Marketplace for {{price}}!',
        description: 'Description',
        no_description_provided: 'No description provided.',
        requested_by: 'Requested By',
        seller_information: 'Seller Information',
        unknown_user: 'Unknown User',
        active_on_campus: 'Active on Campus',
        send_message: 'Send Message',
        message_seller: 'Message Seller',
        user_looking_for: 'User is looking for...',
        just_now: 'Just now',
        minute_ago: '{{count}}m ago',
        hour_ago: '{{count}}h ago',
        day_ago: '{{count}} days ago',
        yesterday: 'Yesterday',
        listed: 'Listed',
        share: 'Share',
        launch: 'Launch',
        new_label: 'New',
        header_new: 'New',
        header_edit: 'Edit',
        mini_community: 'Mini Community',
        listing_label: 'Listing',
        post_placeholder: "What's on your mind?",
        library_label: 'Library',
        camera_label: 'Camera',
        add_event_banner: 'Add event banner',
        ask_label: 'Ask',
        core_problem_placeholder: "What's the core problem?",
        stuck_placeholder: "Explain where you're stuck...",
        add_option_label: 'Add option',
        poll_question_placeholder: 'Ask a question...',
        item_details_label: 'ITEM DETAILS',
        what_selling_placeholder: 'What are you selling?',
        what_looking_placeholder: 'What are you looking for?',
        tell_more_placeholder: 'Tell us more about the item...',
        post_listing_label: 'Post Listing',
        posting_to_label: 'POSTING TO',
        when_label: 'WHEN',
        where_label: 'WHERE',
        venue_placeholder: 'Venue or Link',
        tell_event_more_placeholder: 'Tell everyone more about it...',
        change_cover: 'Change Cover',
        add_event_cover: 'Add Event Cover Photo',
        job_title: 'Job title',
        budget: 'Budget',
        details: 'Details',
        selling: 'Selling',
        requesting: 'Requesting',
        sharing_label: 'Sharing',
        subject_label: 'Subject',
        in_label: 'in',
        setting_time: 'Setting Time...',
        job_tab: 'Jobs',
        study_tab: 'Study',
        activity_header: 'Activity',
        all_caught_up_activity: 'All Caught Up',
        activity_empty_sub: 'Important updates and activity will show up here.',
        add_problem_photo: 'Add a photo of the problem',
        tips_title: 'Quick Tips for Better Help',
        tip_1: 'Be clear and specific in your title.',
        tip_2: 'Show what you\'ve tried—it helps others!',
        tip_3: 'Upload a sharp photo if the problem is visual.',
        save: 'Save',
        wait: 'Wait',
        success: 'Success',
        error: 'Error',
        cancel_label: 'Cancel',
        done_label: 'Done',
        change: 'Change',
        image_selected: 'Image selected',
        option_label: 'Option',
        category: 'Category',
        other: 'Other',
        today: 'Today',
        tomorrow: 'Tomorrow',
        mini_community_hint: 'Starting a study mini-community will allow others to join and collaborate in a dedicated space.',
        mini_community_name_placeholder: 'Mini Community Name (e.g. Bio 101 Study Room)',
        schedule_goal_placeholder: 'Schedule Goal (e.g. Weekends only)',
        group_purpose_placeholder: "What's this group for?",
        fill_all_fields: 'Please fill in all fields',
        question_posted_success: 'Question posted! Good luck!',
        posting_failed: 'Something went wrong while posting',
        community_banner: 'COMMUNITY BANNER',
        community_name: 'NAME',
        community_type: 'TYPE',
        privacy: 'PRIVACY',
        course: 'Course',
        interest: 'Interest',
        club: 'Club',
        study_group: 'Study Group',
        private_community: 'Private Community',
        public_community: 'Public Community',
        private_desc: 'Only members can see posts and content. Join requests need approval.',
        public_desc: 'Anyone can see posts and join freely.',
        add_cover_photo: 'Add cover photo (displayed on community profile)',
        new_community_header: 'New Community',
        schedule_event_header: 'Schedule Event',
        messages_header: 'Messages',
        chat_header: 'Chat',
        study_discussion_header: 'Study Discussion',
        share_pov_header: 'Share POV',
        books: 'Books',
        clothes: 'Clothes',
        accessories: 'Accessories',
        free: 'Free',
        choose_community: 'Choose Community',
        title_label: 'TITLE',
        post_tab: 'Post',
        poll_tab: 'Poll',
        event_tab: 'Events',
        market_tab: 'Market',
        upload_failed: 'Upload Failed',
        description_label: 'Description',
        location_label: 'Location',
        price_label: 'Price',
        event_placeholder: "What's the event?",
        interested_label: 'Interested',
        person_interested: 'person interested',
        people_interested: 'people interested',
        connect_label: 'Connect',
        message_label: 'Message',
        share_profile_label: 'Share Profile',
        campus_rank_label: 'Campus Rank',
        no_content_yet: 'No content yet',
        subject_math: 'Math',
        subject_science: 'Science',
        subject_english: 'English',
        subject_history: 'History',
        subject_physics: 'Physics',
        subject_cs: 'Computer Science',
        subject_business: 'Business',
        subject_arts: 'Arts',
        subject_other: 'Other',
        profile_location: 'Location',
        profile_birthday: 'Birthday',
        profile_relationship: 'Relationship Status',
        profile_class_of: 'Class of',
        profile_graduated: 'Graduated',
        profile_not_graduated: 'Not graduated yet',
        profile_vats: 'Vats',
        notif_all_caught_up: 'All caught up',
        notif_updates_here: 'We will notify you about important updates here',
        notif_now: 'now',
        time_m: 'm',
        time_h: 'h',
        time_d: 'd',
        time_ago: 'ago',
        system_only_message: 'This is a system-only account. You cannot reply to this message.',
        system_account: 'System Account',
        chat_message_placeholder: 'Message...',
        chat_reply: 'Reply',
        chat_copy: 'Copy',
        chat_delete: 'Delete',
        chat_typing: 'is typing...',
        online: 'Online',
        offline: 'Offline',
        edited_label: 'edited',
        'New Poll Vote': 'New Poll Vote',
        'New Join Request': 'New Join Request',
        'New Homework Help Answer!': 'New Homework Help Answer!',
        'New Reply': 'New Reply',
        'New Upvote': 'New Upvote',
        'New Post from Friend': 'New Post from Friend',
        'New Friend Request': 'New Friend Request',
        'New in ': 'New in ',
        'rel_private': 'Private',
        'rel_single': 'Single',
        'rel_in_relationship': 'In a relationship',
        'rel_married': 'Married',
        'rel_complicated': 'Complicated',
    },
    tr: {
        welcome: 'Tekrar Hoş Geldiniz',
        login_subtitle: 'Kampüs ağına erişmek için giriş yapın.',
        email: 'E-posta',
        password: 'Şifre',
        forgot_password: 'Şifremi unuttum?',
        login: 'Giriş Yap',
        no_account: 'Hesabınız yok mu? ',
        apply_access: 'Erişim için başvur',
        create_account: 'Hesap Oluştur',
        register_subtitle: 'Kampüs topluluğunuza katılın ve bağlantıda kalın.',
        full_name: 'Ad Soyad',
        already_account: 'Zaten bir hesabınız var mı? ',
        login_now: 'Giriş yap',
        home: 'Ana Sayfa',
        profile: 'Profil',
        notifications: 'Bildirimler',
        friends: 'Arkadaş',
        settings: 'Ayarlar',
        logout: 'Çıkış yap',
        delete_account: 'Hesabı sil',
        posts: 'Gönderi',
        events: 'Etkinlikler',
        polls: 'Anketler',
        listings: 'İlanlar',
        search: 'Ara',
        connect: 'Bağlan',
        message: 'Mesaj',
        edit_profile: 'Profili Düzenle',
        share_profile: 'Profili Paylaş',
        complete_profile: 'Öne çıkmak için profilini tamamla!',
        bio_placeholder: 'Öğrencilere kendinden bahsetmek için bir biyografi ekle',
        campus_pioneer: 'Kampüs Öncü Sıralaması',
        loading: 'Yükleniyor...',
        feed: 'Akış',
        explore: 'Keşfet',
        marketplace: 'Pazar Yeri',
        study: 'Ders',
        create: 'Oluştur',
        new_post: 'Yeni Gönderi',
        share_with_campus: 'Kampüsünle paylaş',
        new_event: 'Yeni Etkinlik',
        organize_activities: 'Kampüs etkinlikleri düzenle',
        sell_request: 'Sat veya İstek Yap',
        list_on_market: 'Pazarda listele',
        ask_question: 'Soru Sor',
        get_homework_help: 'Ödev yardımı al',
        community_hub: 'Topluluk Merkezi',
        search_communities_placeholder: 'Topluluk ara...',
        search_students_placeholder: 'İsim veya bölümle ara',
        communities_tab: 'Topluluklar',
        students_tab: 'Öğrenciler',
        members_count: 'üye',
        friends_label: 'Arkadaş',
        requested_label: 'İstek Gönderildi',
        add_friend_label: 'Arkadaş Ekle',
        discover_communities: 'Toplulukları keşfet ve katıl',
        start_new_community: 'Yeni Topluluk Başlat',
        no_communities_yet: 'Henüz topluluk yok',
        be_the_first: 'İlk başlatan sen ol!',
        no_students_found: 'Öğrenci bulunamadı',
        try_different_search: 'Farklı bir arama terimi dene',
        all_listings: 'Tüm İlanlar',
        for_sale: 'Satılık',
        requests_tab: 'İstekler',
        items_count: 'Ürün',
        all_communities: 'Tüm Topluluklar',
        filter_by_community: 'Topluluğa Göre Filtrele',
        request_badge: 'İSTEK',
        free_badge: 'ÜCRETSİZ',
        new_badge: 'YENİ',
        looking_for: 'arıyor',
        untitled_item: 'Başlıksız Ürün',
        no_requests_yet: 'Henüz istek yok',
        no_items_for_sale: 'Henüz satılık ürün yok',
        nothing_here_yet: 'Burada henüz bir şey yok',
        be_the_first_to_request: 'İlk istek yapan sen ol!',
        be_the_first_to_list: 'İlk ilan veren sen ol!',
        be_the_first_to_both: 'İlk ilan veren veya istek yapan sen ol!',
        request_an_item: 'Ürün İste',
        sell_an_item: 'Ürün Sat',
        create_a_listing: 'İlan Oluştur',
        all_subjects: 'Hepsi',
        no_questions_in: 'Soru yok:',
        be_the_first_to_ask: 'İlk soran veya yardım eden sen ol!',
        search_messages_placeholder: 'Mesajlarda ara...',
        no_conversations: 'Sohbet yok',
        start_chatting_sub: 'Topluluk üyeleriyle sohbete başla',
        profile_not_found: 'Kullanıcı profili bulunamadı',
        user_blocked: 'Kullanıcı Engellendi',
        profile_unavailable: 'Profil Kullanılamıyor',
        block_desc_me: 'Bu kullanıcıyı engelledin. Etkileşim için engeli kaldır.',
        block_desc_other: 'Bu kullanıcı içeriğini görüntüleyemezsin.',
        unblock_label: 'Engeli Kaldır',
        connect_label: 'Bağlan',
        message_label: 'Mesaj',
        share_profile_label: 'Profili Paylaş',
        no_content_yet: 'Henüz içerik yok',
        campus_rank_label: 'Kampüs Öncü Sıralaması',
        score_label: 'Puan',
        uniscore_label: 'UniScore',
        uniscore_title: 'UniScore nedir?',
        uniscore_body: 'UniScore, UniConn topluluğuna yaptığın pozitif katkıyı gösterir. Gönderi paylaştıkça, yardım ettikçe ve kampüste saygılı etkileşim kurdukça artar.',
        share_profile_title: '{{name}} kullanıcısının Uni profilini incele!',
        share_profile_message: "{{name}} kullanıcısının Uni Hub profilini gör: {{url}}",
        request_cancelled_title: 'İstek iptal edildi',
        request_cancelled_message: 'Bağlantı isteğin geri çekildi.',
        friend_removed_title: 'Arkadaş kaldırıldı',
        friend_removed_message: '{{name}} ile artık arkadaş değilsin.',
        connection_update_failed: 'Bağlantı güncellenemedi. Lütfen tekrar dene.',
        manage_request_title: 'İsteği yönet',
        manage_friendship_title: 'Arkadaşlığı yönet',
        cancel_sent_request: 'Gönderilen isteği iptal et',
        unfriend_student: 'Arkadaştan çıkar',
        connection_request_sent_body: 'Bağlantı isteği başarıyla gönderildi!',
        friends_only_title: 'Sadece arkadaşlar',
        friends_only_body: 'Yalnızca arkadaşlarına mesaj gönderebilirsin. Önce bir bağlantı isteği gönder.',
        profile_options_title: 'Profil seçenekleri',
        block_user_option: 'Kullanıcıyı engelle',
        unblock_user_option: 'Kullanıcının engelini kaldır',
        report_student_option: 'Öğrenciyi bildir',
        spam_or_scam_option: 'Spam veya dolandırıcılık',
        impersonation_option: 'Taklit hesap',
        report_submitted_title: 'Bildirim gönderildi',
        report_submitted_message: 'Topluluğumuzu güvenli tutmaya yardım ettiğin için teşekkürler. Ekibimiz bu bildirimi inceleyecek.',
        report_submit_failed: 'Bildirim gönderilemedi. Lütfen tekrar dene.',
        block_user_title: 'Kullanıcıyı engelle',
        block_user_confirm: '{{name}} kullanıcısını engellemek istediğine emin misin? Sana mesaj gönderemez ve içeriğini göremez.',
        block_user_confirm_action: 'Engelle',
        unblock_user_title: 'Kullanıcının engelini kaldır',
        unblock_user_confirm: '{{name}} kullanıcısının engelini kaldırmak istediğine emin misin?',
        user_blocked_message: '{{name}} engellendi.',
        user_unblocked_title: 'Kullanıcının engeli kaldırıldı',
        user_unblocked_message: '{{name}} kullanıcısının engeli kaldırıldı.',
        block_user_failed: 'Kullanıcı engellenemedi. Tekrar dene.',
        unblock_user_failed: 'Kullanıcının engeli kaldırılamadı. Tekrar dene.',
        uniscore_reputation_title: 'UniScore ve itibar',
        uniscore_reputation_message: 'UniScore kampüsteki etkini yansıtır. Kaynak paylaşarak, etkinlik düzenleyerek ve diğer öğrencilerle etkileşime girerek puan kazan.',
        campus_rank_self_body: 'Pioneer Rank değerin, {{university}} içindeki erken katılım durumunu gösterir. Numara ne kadar küçükse topluluğa o kadar erken katıldın. Bu sıralama kampüsüne özeldir ve kalıcı bir tarih parçasıdır!',
        campus_rank_self_university_fallback: 'üniversiten',
        campus_rank_other_body: '{{name}} kullanıcısının Pioneer Rank değeri, {{university}} içindeki erken katılım durumunu gösterir. Numara ne kadar küçükse topluluğa o kadar erken katılmıştır. Bu sıralama kampüse özeldir ve kalıcı bir tarih parçasıdır!',
        campus_rank_university_fallback: 'üniversitesi',
        post_tab: 'Gönderiler',
        event_tab: 'Etkinlikler',
        poll_tab: 'Anketler',
        market_tab: 'Pazar',
        math: 'Matematik',
        science: 'Fen Bilimleri',
        english: 'İngilizce',
        history: 'Tarih',
        physics: 'Fizik',
        cs: 'Bilgisayar Bilimi',
        business: 'İşletme',
        arts: 'Sanat',
        other: 'Diğer',
        new_community_header: 'Yeni Topluluk',
        messages_header: 'Mesajlar',
        chat_header: 'Sohbet',
        study_discussion_header: 'Ders Tartışması',
        ask_for_help_header: 'Yardım İste',
        schedule_event_header: 'Etkinlik Planla',
        share_pov_header: 'POV Paylaş',
        language: 'Dil',
        lang_en: 'İngilizce',
        lang_tr: 'Türkçe',
        lang_ka: 'Gürcüce',
        books: 'Kitaplar',
        clothes: 'Kıyafetler',
        accessories: 'Aksesuarlar',
        feed_tab: 'Akış',
        events_tab: 'Etkinlikler',
        market_tab_label: 'Pazar',
        list_view: 'Liste',
        calendar_view: 'Takvim',
        community_not_found: 'Topluluk bulunamadı',
        private_community_title: 'Özel Topluluk',
        private_community_body: 'Akışı görmek için bu topluluğa katılmalısın. İçerik gizlidir.',
        request_to_join: 'Katılma isteği gönder',
        cancel_request: 'İsteği iptal et',
        send_to_friends: 'Arkadaşlara gönder',
        search_friends: 'Arkadaş ara…',
        sent: 'Gönderildi',
        send: 'Gönder',
        no_friends_found: 'Arkadaş bulunamadı',
        empty_events: 'Yaklaşan etkinlik yok.',
        empty_market: 'Pazar boş.',
        empty_feed: 'İlk paylaşımı sen yap!',
        enter_chat_room: 'Sohbete gir',
        members_only: 'Sadece üyeler',
        join_to_chat: 'Sohbet için katıl',
        post_something: 'Bir şey paylaş',
        member_status_member: 'Üye',
        member_status_pending: 'İstek gönderildi',
        member_status_request: 'İstek',
        member_status_join: 'Topluluğa katıl',
        admin_creator: 'KURUCUSU',
        study_hub: 'DERS MERKEZİ',
        private_label: 'GİZLİ',
        students_label: 'Öğrenci',
        manage: 'Yönet',
        join_required_title: 'Katılım gerekli',
        join_required_body: 'Sohbete girmek için üye olmalısın.',
        chat_initializing_title: 'Sohbet hazırlanıyor',
        chat_initializing_body: 'Sohbet odası senkronize ediliyor. Lütfen birkaç saniye sonra tekrar dene.',
        retract_request_title: 'İsteği geri çek',
        retract_request_body: 'Bu topluluk için katılma isteğini geri çekmek istiyor musun?',
        leave_community_title: 'Topluluktan ayrıl',
        leave_community_body: 'Topluluktan ayrılmak istediğine emin misin?',
        request_sent_title: 'İstek gönderildi',
        request_sent_body: 'Bu topluluk gizlidir. Bir yönetici isteğini inceleyecek.',
        pulse_title: 'Pulse',
        pulse_rules_title: 'Pulse Kuralları',
        pulse_rules_body: 'Zorbalık yok, isim yok, taciz yok. Kampüsü güvenli tut.',
        pulse_empty_title: 'Pulse boş',
        pulse_empty_sub: 'Düşünceni anonim olarak ilk sen paylaş.',
        pulse_empty_cta: 'Pulse’u başlat',
        pulse_guidelines_title: 'Pulse Topluluk Kuralları',
        pulse_guidelines_body: 'Zorbalık, taciz ve kişileri ifşa etmek yok. Gerçek ol, ama saygılı kal.',
        pulse_input_placeholder: 'Aklında ne var? Anonim olarak paylaş...',
        pulse_create_cta: 'İtiraf Et',
        pulse_posting_as: 'Şu adla gönderiyorsun',
        pulse_beta_notice: 'Pulse beta aşamasında. Özellikler ve davranışlar değişebilir.',
        pulse_uploading_image: 'Görsel yükleniyor...',
        pulse_failed_to_post: 'Anonim gönderi paylaşılamadı',
        pulse_failed_to_edit: 'Anonim gönderi düzenlenemedi',
        pulse_delete_title: 'Pulse Gönderisini Sil',
        pulse_delete_confirm: 'Bu anonim gönderi kalıcı olarak silinecek.',
        pulse_delete_are_you_sure: 'Emin misin?',
        pulse_failed_to_delete: 'Silinemedi',
        pulse_share_prefix: 'Uni Pulse’taki bu anonim gönderiye göz at:',
        pulse_link_copied: 'Anonim gönderi bağlantısı kopyalandı.',
        pulse_report_thanks: 'Teşekkürler. Bu gönderiyi inceleyeceğiz.',
        pulse_options_title: 'Pulse Seçenekleri',
        pulse_report_title: 'Anonim Gönderiyi Bildir',
        pulse_report_bullying: 'Zorbalık veya Taciz',
        pulse_report_hate_speech: 'Nefret Söylemi',
        pulse_anonymous_student: 'Anonim Öğrenci',
        pulse_you_anonymous: 'Sen (anonim)',
        pulse_anon_prefix: 'Anon #',
        pulse_replies_header: 'Anonim Yanıtlar',
        pulse_reply_placeholder: 'Anonim yanıt yaz...',
        pulse_removed_message: 'Bu anonim gönderi kaldırıldı.',
        pulse_not_found_title: 'Bulunamadı',
        pulse_comment_failed: 'Yorum gönderilemedi',
        save: 'Kaydet',
        change_profile_picture: 'Profil fotoğrafını değiştir',
        display_name: 'Görünen Ad',
        username_label: 'Kullanıcı adı',
        personal_details: 'Kişisel Bilgiler (Opsiyonel)',
        hometown: 'Memleket',
        age: 'Yaş',
        relationship_status: 'İlişki durumu',
        select_status: 'Durum seç',
        show_hometown: 'Memleketi göster',
        show_age: 'Yaşı göster',
        show_relationship: 'İlişki durumunu göster',
        academic_details: 'Akademik Bilgiler',
        department_label: 'Bölüm / Ana dal',
        select_department: 'Bölüm seç',
        graduation_year_label: 'Mezuniyet yılı / seviye',
        select_year: 'Yıl/seviye seç',
        show_department: 'Bölümü göster',
        show_year: 'Sınıf/yılı göster',
        show_rank: 'Pioneer sırasını göster',
        success: 'Başarılı',
        profile_updated: 'Profil başarıyla güncellendi!',
        error: 'Hata',
        name_required: 'İsim gerekli',
        upload_failed: 'Yükleme başarısız',
        clear: 'Temizle',
        friend_requests: 'Arkadaş istekleri',
        new_friend_request: 'Yeni arkadaşlık isteği',
        friend_requests_count: '{{count}} arkadaşlık isteği',
        friend_request_banner_single: '{{name}} seninle bağlantı kurmak istiyor',
        friend_request_banner_multiple: 'İnsanlar seninle bağlantı kurmak istiyor',
        wants_to_be_your_friend: 'Seninle arkadaş olmak istiyor',
        no_pending_requests: 'Bekleyen istek yok',
        friend_requests_empty_sub: 'Biri arkadaş olmak istediğinde burada görünecek.',
        accept: 'Kabul et',
        decline: 'Reddet',
        view_all: 'Tümünü gör',
        edit_label: 'Düzenle',
        delete_label: 'Sil',
        edited_label: 'düzenlendi',
        you_badge: 'sen',
        post_header: 'Gönderi',
        post_not_found: 'Gönderi bulunamadı',
        no_replies_yet: 'Henüz yanıt yok. İlk sen yaz.',
        failed_to_post_comment: 'Yorum gönderilemedi',
        delete_comment_title: 'Yorumu Sil',
        delete_comment_confirm: 'Bu yorumu silmek istediğine emin misin?',
        failed_to_delete_comment: 'Yorum silinemedi',
        willing_to_pay: 'Ödeyebileceğim',
        looking_for_label: 'Arıyor',
        help_source: 'Kaynak Bul',
        view_item: 'Ürünü Gör',
        anonymous_user: 'Anonim',
        event_badge: 'ETKİNLİK',
        passed_label: 'GEÇTİ',
        interested_label: 'İlgileniyorum',
        person_label: 'kişi',
        people_label: 'kişi',
        event_details_header: 'Etkinlik Detayları',
        event_already_ended: 'Bu etkinlik zaten sona erdi.',
        loading_event: 'Etkinlik yükleniyor...',
        community_label: 'Topluluk',
        person_is_interested: 'kişi ilgileniyor',
        people_are_interested: 'kişi ilgileniyor',
        about_this_event: 'Bu etkinlik hakkında',
        no_event_description: 'Açıklama eklenmemiş.',
        im_interested_label: 'İlgileniyorum',
        mark_as_interested: 'İlgileniyorum olarak işaretle',
        done_label: 'Tamam',
        marked_as_status: '{{status}} olarak işaretlendin!',
        poll_badge: 'ANKET',
        votes_label: 'oy',
        tap_to_vote: 'Oy vermek için dokun',
        share_option: 'Paylaş',
        copy_link_option: 'Bağlantıyı Kopyala',
        report_option: 'Bildir',
        edit_post_option: 'Gönderiyi Düzenle',
        post_options_title: 'Gönderi Seçenekleri',
        poll_options_title: 'Anket Seçenekleri',
        marketplace_listing_title: 'Pazar İlanı',
        why_reporting_title: 'Neden bildiriyorsun?',
        inappropriate_content_option: 'Uygunsuz İçerik',
        harassment_option: 'Taciz',
        spam_option: 'Spam',
        scam_option: 'Dolandırıcılık',
        link_copied_title: 'Bağlantı Kopyalandı',
        post_link_copied: 'Gönderi bağlantısı panoya kopyalandı.',
        listing_link_copied: 'İlan bağlantısı panoya kopyalandı.',
        poll_link_copied: 'Anket bağlantısı panoya kopyalandı.',
        notifications_label: 'Bildirimler',
        theme: 'Tema',
        select_theme: 'Tema Seç',
        theme_light: 'Açık',
        theme_dark: 'Koyu',
        theme_system: 'Sistem',
        privacy_policy: 'Gizlilik Politikası',
        terms_of_use: 'Kullanım Şartları',
        privacy_desc: 'Verilerini nasıl koruyoruz',
        terms_desc: 'Öğrenci topluluğu kuralları',
        logout_label: 'Çıkış yap',
        delete_account_label: 'Hesabı sil',
        no_items_yet: 'Henüz içerik yok',
        score: 'Puan',
        pulse_rules_prefix: 'Pulse Kuralları:',
        listed: 'Listelendi',
        study_question_not_found: 'Soru bulunamadı',
        study_answers: 'Yanıtlar',
        study_empty_answers: 'Henüz kimse yanıtlamadı.',
        study_empty_answers_sub: 'İlk yardım eden sen ol!',
        study_answer_placeholder: 'Yanıtını veya açıklamanı yaz...',
        study_post_answer_failed: 'Yanıt gönderilemedi',
        you_tag: '(Sen)',
        market_listing_fallback: 'İlan...',
        market_item_not_found: 'İlan bulunamadı',
        go_back: 'Geri dön',
        market_share_text: '{{title}} ürününe Pazaryerinde {{price}} fiyatla göz at!',
        description: 'Açıklama',
        no_description_provided: 'Açıklama eklenmemiş.',
        requested_by: 'İsteyen',
        seller_information: 'Satıcı Bilgisi',
        unknown_user: 'Bilinmeyen kullanıcı',
        active_on_campus: 'Kampüste aktif',
        send_message: 'Mesaj Gönder',
        message_seller: 'Satıcıya Mesaj',
        user_looking_for: 'Kullanıcı arıyor...',
        reply: 'Yanıt',
        replies: 'Yanıtlar',
        help_out: 'Yardım et',
        replying_to: 'Yanıtlıyor',
        write_comment_placeholder: 'Yorum yaz…',
        new_message: 'Yeni mesaj',
        you_received_a_new_message: 'Yeni bir mesaj aldın',
        group_chat: 'Grup sohbeti',
        activity_header: 'Bildirimler',
        all_caught_up_activity: 'Hepsi okundu',
        activity_empty_sub: 'Önemli güncellemeleri burada bildireceğiz',
        cancel_label: 'İptal',
        cancel_request: 'İsteği iptal et',
        send_to_friends: 'Arkadaşlara gönder',
        search_friends: 'Arkadaş ara…',
        sent: 'Gönderildi',
        send: 'Gönder',
        no_friends_found: 'Arkadaş bulunamadı',
        no_messages_yet: 'Henüz mesaj yok',
        you_shared_post: 'Bu gönderiyi paylaştın',
        someone_shared_post: '{{name}} bu gönderiyi paylaştı',
        video_label: 'Video',
        photo_label: 'Foto',
        user_fallback: 'Kullanıcı',
        group_fallback: 'Grup',
        conversation_options: 'Sohbet Seçenekleri',
        clear_history: 'Geçmişi Temizle',
        private_label: 'GİZLİ',
        join_required_title: 'Katılım gerekli',
        join_required_body: 'Bu içeriği görmek için üye olmalısın.',
        request_sent_title: 'İstek gönderildi',
        request_sent_body: 'Bir yönetici isteğini inceleyecek.',
        leave_community_title: 'Topluluktan ayrıl',
        leave_community_body: 'Bu topluluktan ayrılmak istiyor musun?',
        retract_request_title: 'İsteği geri çek',
        retract_request_body: 'Katılma isteğini geri çekmek istiyor musun?',
        members_only: 'Sadece üyeler',
        join_to_chat: 'Sohbet için katıl',
        enter_chat_room: 'Sohbete gir',
        post_something: 'Bir şey paylaş',
        admin_creator: 'KURUCUSU',
        students_label: 'Öğrenci',
        manage: 'Yönet',
        locked_body: 'Akışı görmek için bu topluluğa katıl. İçerik gizlidir.',
        just_now: 'Hemen şimdi',
        minute_ago: '{{count}} dk önce',
        hour_ago: '{{count}} sa önce',
        yesterday: 'Dün',
        share: 'Paylaş',
        launch: 'Başlat',
        new_label: 'Yeni',
        header_new: 'Yeni',
        header_edit: 'Düzenle',
        mini_community: 'Mini Topluluk',
        listing_label: 'İlan',
        post_placeholder: 'Neler düşünüyorsun?',
        library_label: 'Kütüphane',
        camera_label: 'Kamera',
        add_event_banner: 'Etkinlik afişi ekle',
        ask_label: 'Sor',
        core_problem_placeholder: 'Temel sorun nedir?',
        stuck_placeholder: 'Nerede takıldığını açıkla...',
        add_option_label: 'Seçenek ekle',
        poll_question_placeholder: 'Bir soru sor...',
        item_details_label: 'ÜRÜN DETAYLARI',
        what_selling_placeholder: 'Ne satıyorsun?',
        what_looking_placeholder: 'Ne arıyorsun?',
        tell_more_placeholder: 'Ürün hakkında daha fazla bilgi ver...',
        post_listing_label: 'İlanı Paylaş',
        posting_to_label: 'PAYLAŞILAN YER',
        when_label: 'NE ZAMAN',
        where_label: 'NEREDE',
        venue_placeholder: 'Mekan veya Bağlantı',
        tell_event_more_placeholder: 'Etkinlik hakkında daha fazla bilgi ver...',
        change_cover: 'Kapağı Değiştir',
        add_event_cover: 'Etkinlik Kapak Fotoğrafı Ekle',
        job_title: 'İş başlığı',
        budget: 'Bütçe',
        details: 'Detaylar',
        selling: 'Satış',
        requesting: 'İstek',
        sharing_label: 'Paylaşılıyor',
        subject_label: 'Konu',
        in_label: 'şurada',
        setting_time: 'Zaman ayarlanıyor...',
        job_tab: 'İşler',
        study_tab: 'Ders',
        add_problem_photo: 'Problemin fotoğrafını ekle',
        tips_title: 'Daha İyi Yardım İçin İpuçları',
        tip_1: 'Başlığınızda net ve spesifik olun.',
        tip_2: 'Neler denediğinizi gösterin—başkalarına yardımcı olur!',
        tip_3: 'Problem görselse net bir fotoğraf yükleyin.',
        save: 'Kaydet',
        wait: 'Bekle',
        success: 'Başarılı',
        error: 'Hata',
        cancel_label: 'İptal',
        done_label: 'Bitti',
        change: 'Değiştir',
        image_selected: 'Resim seçildi',
        option_label: 'Seçenek',
        category: 'Kategori',
        other: 'Diğer',
        today: 'Bugün',
        tomorrow: 'Yarın',
        mini_community_hint: 'Bir çalışma mini topluluğu başlatmak, başkalarının katılmasına ve özel bir alanda işbirliği yapmasına olanak tanır.',
        mini_community_name_placeholder: 'Mini Topluluk Adı (örn. Biyo 101 Çalışma Odası)',
        schedule_goal_placeholder: 'Program Hedefi (örn. Sadece hafta sonları)',
        group_purpose_placeholder: 'Bu grup ne için?',
        fill_all_fields: 'Lütfen tüm alanları doldurun',
        question_posted_success: 'Soru paylaşıldı! İyi şanslar!',
        posting_failed: 'Paylaşırken bir şeyler yanlış gitti',
        community_banner: 'TOPLULUK AFIŞI',
        community_name: 'AD',
        community_type: 'TÜR',
        privacy: 'GİZLİLİK',
        course: 'Ders',
        interest: 'İlgi Alanı',
        club: 'Kulüp',
        study_group: 'Çalışma Grubu',
        private_community: 'Gizli Topluluk',
        public_community: 'Açık Topluluk',
        private_desc: 'Sadece üyeler gönderileri ve içeriği görebilir. Katılım istekleri onay gerektirir.',
        public_desc: 'Herkes gönderileri görebilir ve serbestçe katılabilir.',
        add_cover_photo: 'Kapak fotoğrafı ekle (topluluk profilinde görünür)',
        new_community_header: 'Yeni Topluluk',
        schedule_event_header: 'Etkinlik Planla',
        messages_header: 'Mesajlar',
        chat_header: 'Sohbet',
        study_discussion_header: 'Ders Tartışması',
        share_pov_header: 'Bakış Açısı Paylaş',
        books: 'Kitap',
        clothes: 'Kıyafet',
        accessories: 'Aksesuar',
        free: 'Ücretsiz',
        choose_community: 'Topluluk Seç',
        title_label: 'BAŞLIK',
        post_tab: 'Gönderi',
        poll_tab: 'Anket',
        event_tab: 'Etkinlikler',
        market_tab: 'Pazar',
        upload_failed: 'Yükleme Başarısız',
        description_label: 'Açıklama',
        location_label: 'Konum',
        price_label: 'Fiyat',
        event_placeholder: 'Etkinlik ne hakkında?',
        interested_label: 'İlgileniyorum',
        person_interested: 'kişi ilgileniyor',
        people_interested: 'kişi ilgileniyor',
        connect_label: 'Bağlan',
        message_label: 'Mesaj',
        share_profile_label: 'Profili Paylaş',
        campus_rank_label: 'Kampüs Sıralaması',
        no_content_yet: 'Henüz içerik yok',
        subject_math: 'Matematik',
        subject_science: 'Bilim',
        subject_english: 'İngilizce',
        subject_history: 'Tarih',
        subject_physics: 'Fizik',
        subject_cs: 'Bilgisayar Bilimi',
        subject_business: 'İşletme',
        subject_arts: 'Sanat',
        subject_other: 'Diğer',
        profile_location: 'Konum',
        profile_birthday: 'Doğum Günü',
        profile_relationship: 'İlişki Durumu',
        profile_class_of: 'Sınıf',
        profile_graduated: 'Mezun',
        profile_not_graduated: 'Henüz mezun değil',
        profile_vats: 'Vats',
        notif_all_caught_up: 'Hepsini gördün',
        notif_updates_here: 'Önemli güncellemeler burada bildirilecek',
        notif_now: 'şimdi',
        time_m: 'dk',
        time_h: 'sa',
        time_d: 'g',
        time_ago: 'önce',
        system_only_message: 'Bu sadece sistem hesabıdır. Bu mesaja yanıt veremezsiniz.',
        system_account: 'Sistem Hesabı',
        chat_message_placeholder: 'Mesaj...',
        chat_reply: 'Yanıtla',
        chat_copy: 'Kopyala',
        chat_delete: 'Sil',
        chat_typing: 'yazıyor...',
        online: 'Çevrimiçi',
        offline: 'Çevrimdışı',
        edited_label: 'düzenlendi',
        'New Poll Vote': 'Yeni Anket Oyu',
        'New Join Request': 'Yeni Katılma İsteği',
        'New Homework Help Answer!': 'Yeni Ödev Yardımı Cevabı!',
        'New Reply': 'Yeni Yanıt',
        'New Upvote': 'Yeni Beğeni',
        'New Post from Friend': 'Arkadaştan Yeni Gönderi',
        'New Friend Request': 'Yeni Arkadaşlık İsteği',
        'New in ': 'Yeni: ',
        'rel_private': 'Gizli',
        'rel_single': 'Bekar',
        'rel_in_relationship': 'İlişkisi var',
        'rel_married': 'Evli',
        'rel_complicated': 'Karmaşık',
    },
    ka: {
        welcome: 'მოგესალმებით',
        login_subtitle: 'შედით სისტემაში თქვენს კამპუსურ ქსელზე წვდომისთვის.',
        email: 'ელ-ფოსტა',
        password: 'პაროლი',
        forgot_password: 'დაგავიწყდათ პაროლი?',
        login: 'შესვლა',
        no_account: 'არ გაქვთ ანგარიში? ',
        apply_access: 'მოითხოვეთ წვდომა',
        create_account: 'ანგარიშის შექმნა',
        register_subtitle: 'შეუერთდით თქვენს კამპუსურ საზოგადოებას.',
        full_name: 'სრული სახელი',
        already_account: 'უკვე გაქვთ ანგარიში? ',
        login_now: 'შესვლა',
        home: 'მთავარი',
        profile: 'პროფილი',
        notifications: 'შეტყობინებები',
        friends: 'მეგობრები',
        settings: 'პარამეტრები',
        logout: 'გასვლა',
        delete_account: 'ანგარიშის წაშლა',
        posts: 'პოსტები',
        events: 'ღონისძიებები',
        polls: 'გამოკითხვები',
        listings: 'განცხადებები',
        search: 'ძებნა',
        connect: 'დაკავშირება',
        message: 'შეტყობინება',
        edit_profile: 'პროფილის რედაქტირება',
        share_profile: 'პროფილის გაზიარება',
        complete_profile: 'შეავსეთ პროფილი გამოსაჩენად!',
        bio_placeholder: 'დაამატეთ ბიოგრაფია თქვენს შესახებ',
        campus_pioneer: 'კამპუსის პიონერის რანგი',
        loading: 'იტვირთება...',
        feed: 'არხი',
        explore: 'აღმოაჩინე',
        marketplace: 'მარკეტი',
        study: 'სწავლა',
        create: 'შექმნა',
        new_post: 'ახალი პოსტი',
        share_with_campus: 'გაუზიარე კამპუსს',
        new_event: 'ახალი ღონისძიება',
        organize_activities: 'დაგეგმე აქტივობები',
        sell_request: 'გაყიდე ან მოითხოვე',
        list_on_market: 'დაამატე მარკეტში',
        ask_question: 'კითხვის დასმა',
        get_homework_help: 'დახმარება დავალებაში',
        community_hub: 'საზოგადოება',
        search_communities_placeholder: 'მოძებნე თემები...',
        search_students_placeholder: 'სახელით ან დეპარტამენტით',
        communities_tab: 'თემები',
        students_tab: 'სტუდენტები',
        members_count: 'წევრი',
        friends_label: 'მეგობრები',
        requested_label: 'მოთხოვნილია',
        add_friend_label: 'დამატება',
        discover_communities: 'აღმოაჩინე და შეუერთდი',
        start_new_community: 'ახალი თემის შექმნა',
        no_communities_yet: 'თემები არ არის',
        be_the_first: 'იყავი პირველი!',
        no_students_found: 'სტუდენტები ვერ მოიძებნა',
        try_different_search: 'სცადე სხვა სიტყვა',
        all_listings: 'ყველა განცხადება',
        for_sale: 'იყიდება',
        requests_tab: 'მოთხოვნები',
        items_count: 'ნივთი',
        all_communities: 'ყველა თემი',
        filter_by_community: 'გაფილტრე თემით',
        request_badge: 'მოთხოვნა',
        free_badge: 'უფასო',
        new_badge: 'ახალი',
        looking_for: 'ეძებს',
        untitled_item: 'უსახელო ნივთი',
        no_requests_yet: 'მოთხოვნები არ არის',
        no_items_for_sale: 'განცხადებები არ არის',
        nothing_here_yet: 'აქ არაფერია',
        be_the_first_to_request: 'იყავი პირველი ვინც მოითხოვს!',
        be_the_first_to_list: 'იყავი პირველი ვინც დადებს!',
        be_the_first_to_both: 'იყავი პირველი ვინც დადებს!',
        request_an_item: 'ითხოვე ნივთი',
        sell_an_item: 'გაყიდე ნივთი',
        create_a_listing: 'დადე განცხადება',
        all_subjects: 'ყველა',
        no_questions_in: 'კითხვები არ არის:',
        be_the_first_to_ask: 'იყავი პირველი ვინც იკითხავს!',
        search_messages_placeholder: 'მოძებნე შეტყობინებები...',
        no_conversations: 'საუბრები არ არის',
        start_chatting_sub: 'დაიწყე მიმოწერა წევრებთან',
        profile_not_found: 'პროფილი ვერ მოიძებნა',
        user_blocked: 'დაბლოკილია',
        profile_unavailable: 'პროფილი მიუწვდომელია',
        block_desc_me: 'თქვენ დაბლოკეთ ეს მომხმარებელი.',
        block_desc_other: 'თქვენ ვერ ხედავთ ამ მომხმარებელს.',
        unblock_label: 'განბლოკვა',
        connect_label: 'დამატება',
        message_label: 'მიწერა',
        share_profile_label: 'გაზიარება',
        no_content_yet: 'კონტენტი არ არის',
        campus_rank_label: 'კამპუსის პიონერის რანგი',
        score_label: 'ქულა',
        uniscore_label: 'UniScore',
        uniscore_title: 'რა არის UniScore?',
        uniscore_body: 'UniScore აჩვენებს შენს პოზიტიურ წვლილს UniConn-ზე. ქულა იზრდება, როცა აქვეყნებ, ეხმარები სხვებს და პატივისცემით ერთვები კამპუსურ სივრცეში.',
        share_profile_title: 'ნახე {{name}}-ის Uni პროფილი!',
        share_profile_message: 'ნახე {{name}}-ის სტუდენტური პროფილი Uni Hub-ში: {{url}}',
        request_cancelled_title: 'მოთხოვნა გაუქმდა',
        request_cancelled_message: 'შენი დაკავშირების მოთხოვნა გაუქმდა.',
        friend_removed_title: 'მეგობარი წაიშალა',
        friend_removed_message: 'აღარ ხარ {{name}}-ის მეგობარი.',
        connection_update_failed: 'კავშირის განახლება ვერ მოხერხდა. სცადე თავიდან.',
        manage_request_title: 'მოთხოვნის მართვა',
        manage_friendship_title: 'მეგობრობის მართვა',
        cancel_sent_request: 'გაგზავნილი მოთხოვნის გაუქმება',
        unfriend_student: 'მეგობრობიდან წაშლა',
        connection_request_sent_body: 'დაკავშირების მოთხოვნა წარმატებით გაიგზავნა!',
        friends_only_title: 'მხოლოდ მეგობრები',
        friends_only_body: 'მიწერა მხოლოდ მეგობრებს შეგიძლია. ჯერ გააგზავნე დაკავშირების მოთხოვნა.',
        profile_options_title: 'პროფილის პარამეტრები',
        block_user_option: 'მომხმარებლის დაბლოკვა',
        unblock_user_option: 'მომხმარებლის განბლოკვა',
        report_student_option: 'სტუდენტის გასაჩივრება',
        spam_or_scam_option: 'სპამი ან თაღლითობა',
        impersonation_option: 'სხვის სახელით წარმოდგენა',
        report_submitted_title: 'საჩივარი გაიგზავნა',
        report_submitted_message: 'გმადლობთ, რომ გვეხმარები საზოგადოების უსაფრთხოების დაცვაში. ჩვენი გუნდი ამ საჩივარს გადაამოწმებს.',
        report_submit_failed: 'საჩივრის გაგზავნა ვერ მოხერხდა. სცადე თავიდან.',
        block_user_title: 'მომხმარებლის დაბლოკვა',
        block_user_confirm: 'ნამდვილად გინდა {{name}}-ის დაბლოკვა? ის ვეღარ მოგწერს და ვეღარ ნახავს შენს კონტენტს.',
        block_user_confirm_action: 'დაბლოკვა',
        unblock_user_title: 'მომხმარებლის განბლოკვა',
        unblock_user_confirm: 'ნამდვილად გინდა {{name}}-ის განბლოკვა?',
        user_blocked_message: '{{name}} დაიბლოკა.',
        user_unblocked_title: 'მომხმარებელი განბლოკილია',
        user_unblocked_message: '{{name}} განბლოკილია.',
        block_user_failed: 'მომხმარებლის დაბლოკვა ვერ მოხერხდა. სცადე თავიდან.',
        unblock_user_failed: 'მომხმარებლის განბლოკვა ვერ მოხერხდა. სცადე თავიდან.',
        uniscore_reputation_title: 'UniScore და რეპუტაცია',
        uniscore_reputation_message: 'UniScore აჩვენებს შენს გავლენას კამპუსში. ქულებს იღებ, როცა აზიარებ რესურსებს, აწყობ ღონისძიებებს და ერთვები სხვა სტუდენტებთან.',
        campus_rank_self_body: 'შენი Pioneer Rank აჩვენებს შენს ადრეულ ჩართულობას {{university}}-ში. რაც უფრო დაბალია რიცხვი, მით უფრო ადრე შეუერთდი საზოგადოებას. ეს რანგი უნიკალურია შენი კამპუსისთვის და მუდმივ ისტორიად რჩება!',
        campus_rank_self_university_fallback: 'შენს უნივერსიტეტში',
        campus_rank_other_body: '{{name}}-ის Pioneer Rank აჩვენებს მის ადრეულ ჩართულობას {{university}}-ში. რაც უფრო დაბალია რიცხვი, მით უფრო ადრე შეუერთდა საზოგადოებას. ეს რანგი უნიკალურია კამპუსისთვის და მუდმივ ისტორიად რჩება!',
        campus_rank_university_fallback: 'მის უნივერსიტეტში',
        post_tab: 'პოსტები',
        event_tab: 'ღონისძიებები',
        poll_tab: 'გამოკითხვები',
        market_tab: 'მარკეტი',
        math: 'მათემატიკა',
        science: 'მეცნიერება',
        english: 'ინგლისური',
        history: 'ისტორია',
        physics: 'ფიზიკა',
        cs: 'კომპ. მეცნიერება',
        business: 'ბიზნესი',
        arts: 'ხელოვნება',
        other: 'სხვა',
        new_community_header: 'ახალი თემი',
        messages_header: 'შეტყობინებები',
        chat_header: 'ჩატი',
        study_discussion_header: 'სწავლის განხილვა',
        ask_for_help_header: 'ითხოვე დახმარება',
        schedule_event_header: 'დაგეგმე ღონისძიება',
        share_pov_header: 'გააზიარე POV',
        language: 'ენა',
        lang_en: 'ინგლისური',
        lang_tr: 'თურქული',
        lang_ka: 'ქართული',
        books: 'წიგნები',
        clothes: 'ტანსაცმელი',
        accessories: 'აქსესუარები',
        feed_tab: 'არხი',
        events_tab: 'ღონისძიებები',
        market_tab_label: 'მარკეტი',
        list_view: 'სია',
        calendar_view: 'კალენდარი',
        community_not_found: 'თემი ვერ მოიძებნა',
        private_community_title: 'დახურული თემი',
        private_community_body: 'თემის ყურებისთვის შეუერთდი. კონტენტი დაცულია.',
        request_to_join: 'გაგზავნე მოთხოვნა',
        cancel_request: 'მოთხოვნის გაუქმება',
        empty_events: 'ღონისძიებები არ არის.',
        empty_market: 'მარკეტი ცარიელია.',
        empty_feed: 'პირველი გააზიარე რამე!',
        enter_chat_room: 'ჩატში შესვლა',
        members_only: 'მხოლოდ წევრები',
        join_to_chat: 'ჩატისთვის შეერთდი',
        post_something: 'რაღაც გამოაქვეყნე',
        member_status_member: 'წევრი',
        member_status_pending: 'მოთხოვნა გაგზავნილია',
        member_status_request: 'მოთხოვნა',
        member_status_join: 'შეუერთდი თემს',
        admin_creator: 'ადმინისტრატორი',
        study_hub: 'სასწავლო სივრცე',
        private_label: 'დახურული',
        students_label: 'სტუდენტი',
        manage: 'მართვა',
        join_required_title: 'საჭიროა შეერთება',
        join_required_body: 'ჩატში შესასვლელად უნდა იყო წევრი.',
        chat_initializing_title: 'ჩატი იტვირთება',
        chat_initializing_body: 'ჩატის ოთახი სინქრონიზდება. სცადე რამდენიმე წამში.',
        retract_request_title: 'მოთხოვნის გაუქმება',
        retract_request_body: 'დარწმუნებული ხარ, რომ გინდა გააუქმო თხოვნა?',
        leave_community_title: 'თემიდან გასვლა',
        leave_community_body: 'დარწმუნებული ხარ, რომ გინდა დატოვო თემი?',
        request_sent_title: 'მოთხოვნა გაგზავნილია',
        request_sent_body: 'ეს თემი დახურულია. ადმინი განიხილავს.',
        pulse_title: 'Pulse',
        pulse_rules_title: 'Pulse წესები',
        pulse_rules_body: 'არავითარი ბულინგი, სახელები და შევიწროება. დაიცავი კამპუსი.',
        pulse_empty_title: 'Pulse ცარიელია',
        pulse_empty_sub: 'პირველი თქვი შენი აზრი ანონიმურად.',
        pulse_empty_cta: 'დაამატე პოსტი',
        pulse_guidelines_title: 'Pulse საზოგადოების წესები',
        pulse_guidelines_body: 'ბულინგი, შევიწროება და ადამიანების დასახელება აკრძალულია. იყავი გულწრფელი და პატივისცემით იურთიერთე.',
        pulse_input_placeholder: 'რა გაქვს სათქმელი? დაწერე ანონიმურად...',
        pulse_create_cta: 'აღიარე',
        pulse_posting_as: 'აქვეყნებ როგორც',
        pulse_beta_notice: 'Pulse ბეტა რეჟიმშია. ფუნქციები და ქცევა შეიძლება შეიცვალოს.',
        pulse_uploading_image: 'სურათი იტვირთება...',
        pulse_failed_to_post: 'ანონიმური პოსტის დამატება ვერ მოხერხდა',
        pulse_failed_to_edit: 'ანონიმური პოსტის განახლება ვერ მოხერხდა',
        pulse_delete_title: 'Pulse პოსტის წაშლა',
        pulse_delete_confirm: 'ეს ანონიმური პოსტი საბოლოოდ წაიშლება.',
        pulse_delete_are_you_sure: 'დარწმუნებული ხარ?',
        pulse_failed_to_delete: 'წაშლა ვერ მოხერხდა',
        pulse_share_prefix: 'ნახე ეს ანონიმური პოსტი Uni Pulse-ში:',
        pulse_link_copied: 'ანონიმური პოსტის ბმული დაკოპირდა.',
        pulse_report_thanks: 'გმადლობთ. ამ პოსტს შევამოწმებთ.',
        pulse_options_title: 'Pulse პარამეტრები',
        pulse_report_title: 'ანონიმური პოსტის გასაჩივრება',
        pulse_report_bullying: 'ბულინგი ან შევიწროება',
        pulse_report_hate_speech: 'სიძულვილის ენა',
        pulse_anonymous_student: 'ანონიმური სტუდენტი',
        pulse_you_anonymous: 'შენ (ანონიმურად)',
        pulse_anon_prefix: 'ანონ #',
        pulse_replies_header: 'ანონიმური პასუხები',
        pulse_reply_placeholder: 'უპასუხე ანონიმურად...',
        pulse_removed_message: 'ეს ანონიმური პოსტი წაიშალა.',
        pulse_not_found_title: 'ვერ მოიძებნა',
        pulse_comment_failed: 'კომენტარის დამატება ვერ მოხერხდა',
        save: 'შენახვა',
        change_profile_picture: 'პროფილის სურათის შეცვლა',
        display_name: 'სახელი',
        username_label: 'მომხმარებელი',
        personal_details: 'პირადი დეტალები (არჩევითი)',
        hometown: 'ქალაქი',
        age: 'ასაკი',
        relationship_status: 'ურთიერთობის სტატუსი',
        select_status: 'აირჩიე სტატუსი',
        show_hometown: 'ქალაქის ჩვენება',
        show_age: 'ასაკის ჩვენება',
        show_relationship: 'სტატუსის ჩვენება',
        academic_details: 'აკადემიური დეტალები',
        department_label: 'ფაკულტეტი / მიმართულება',
        select_department: 'აირჩიე მიმართულება',
        graduation_year_label: 'დამთავრების წელი / დონე',
        select_year: 'აირჩიე წელი/დონე',
        show_department: 'ფაკულტეტის ჩვენება',
        show_year: 'დონის ჩვენება',
        show_rank: 'რანგის ჩვენება',
        success: 'წარმატება',
        profile_updated: 'პროფილი განახლდა!',
        error: 'შეცდომა',
        name_required: 'სახელი საჭიროა',
        upload_failed: 'ატვირთვა ვერ მოხერხდა',
        clear: 'გასუფთავება',
        friend_requests: 'მეგობრობის მოთხოვნები',
        new_friend_request: 'ახალი მეგობრობის მოთხოვნა',
        friend_requests_count: '{{count}} მეგობრობის მოთხოვნა',
        friend_request_banner_single: '{{name}}-ს შენთან დაკავშირება სურს',
        friend_request_banner_multiple: 'რამდენიმე ადამიანს სურს შენთან დაკავშირება',
        wants_to_be_your_friend: 'სურს შენი მეგობარი გახდეს',
        no_pending_requests: 'მოლოდინის მოთხოვნები არ არის',
        friend_requests_empty_sub: 'როცა ვინმეს მოუნდება დამეგობრება, აქ გამოჩნდება.',
        accept: 'დადასტურება',
        decline: 'უარყოფა',
        view_all: 'ყველას ნახვა',
        edit_label: 'ჩასწორება',
        delete_label: 'წაშლა',
        edited_label: 'ჩასწორებულია',
        you_badge: 'შენ',
        post_header: 'პოსტი',
        post_not_found: 'პოსტი ვერ მოიძებნა',
        no_replies_yet: 'ჯერ პასუხები არ არის. იყავი პირველი.',
        failed_to_post_comment: 'კომენტარის გამოქვეყნება ვერ მოხერხდა',
        delete_comment_title: 'კომენტარის წაშლა',
        delete_comment_confirm: 'ნამდვილად გსურს ამ კომენტარის წაშლა?',
        failed_to_delete_comment: 'კომენტარის წაშლა ვერ მოხერხდა',
        willing_to_pay: 'გადავიხდი',
        looking_for_label: 'ეძებს',
        help_source: 'წყაროს დახმარება',
        view_item: 'ნივთის ნახვა',
        anonymous_user: 'ანონიმური',
        event_badge: 'ღონისძიება',
        passed_label: 'დასრულდა',
        interested_label: 'დაინტერესებული',
        person_label: 'ადამიანი',
        people_label: 'ადამიანი',
        event_details_header: 'ღონისძიების დეტალები',
        event_already_ended: 'ეს ღონისძიება უკვე დასრულდა.',
        loading_event: 'ღონისძიება იტვირთება...',
        community_label: 'საზოგადოება',
        person_is_interested: 'ადამიანი არის დაინტერესებული',
        people_are_interested: 'ადამიანი არის დაინტერესებული',
        about_this_event: 'ამ ღონისძიების შესახებ',
        no_event_description: 'აღწერა არ არის დამატებული.',
        im_interested_label: 'დაინტერესებული ვარ',
        mark_as_interested: 'მონიშნე როგორც დაინტერესებული',
        done_label: 'მზადაა',
        marked_as_status: 'მონიშნული ხარ როგორც {{status}}!',
        poll_badge: 'გამოკითხვა',
        votes_label: 'ხმა',
        tap_to_vote: 'დააჭირე ხმის მისაცემად',
        share_option: 'გაზიარება',
        copy_link_option: 'ბმულის კოპირება',
        report_option: 'გასაჩივრება',
        edit_post_option: 'პოსტის ჩასწორება',
        post_options_title: 'პოსტის პარამეტრები',
        poll_options_title: 'გამოკითხვის პარამეტრები',
        marketplace_listing_title: 'მარკეტის განცხადება',
        why_reporting_title: 'რატომ აჩივრებ?',
        inappropriate_content_option: 'შეუფერებელი კონტენტი',
        harassment_option: 'შევიწროება',
        spam_option: 'სპამი',
        scam_option: 'თაღლითობა',
        link_copied_title: 'ბმული დაკოპირდა',
        post_link_copied: 'პოსტის ბმული დაკოპირდა ბუფერში.',
        listing_link_copied: 'განცხადების ბმული დაკოპირდა ბუფერში.',
        poll_link_copied: 'გამოკითხვის ბმული დაკოპირდა ბუფერში.',
        notifications_label: 'შეტყობინებები',
        theme: 'თემა',
        select_theme: 'თემის არჩევა',
        theme_light: 'ნათელი',
        theme_dark: 'მუქი',
        theme_system: 'სისტემური',
        privacy_policy: 'კონფიდენციალურობა',
        terms_of_use: 'გამოყენების პირობები',
        privacy_desc: 'როგორ ვიცავთ მონაცემებს',
        terms_desc: 'ჩვენი საზოგადოების წესები',
        logout_label: 'გასვლა',
        delete_account_label: 'ანგარიშის წაშლა',
        no_items_yet: 'ჯერ არაფერია',
        score: 'ქულა',
        pulse_rules_prefix: 'Pulse წესები:',
        listed: 'დალისტდა',
        study_question_not_found: 'კითხვა ვერ მოიძებნა',
        study_answers: 'პასუხები',
        study_empty_answers: 'ჯერ არავის უპასუხია.',
        study_empty_answers_sub: 'იყავი პირველი ვინც დაეხმარება!',
        study_answer_placeholder: 'დაწერე შენი პასუხი ან ახსნა...',
        study_post_answer_failed: 'პასუხის გამოქვეყნება ვერ მოხერხდა',
        you_tag: '(შენ)',
        market_listing_fallback: 'განცხადება...',
        market_item_not_found: 'განცხადება ვერ მოიძებნა',
        go_back: 'უკან დაბრუნება',
        market_share_text: 'ნახე {{title}} მარკეტში {{price}} ფასად!',
        description: 'აღწერა',
        no_description_provided: 'აღწერა არ არის მითითებული.',
        requested_by: 'მომთხოვნი',
        seller_information: 'გამყიდველის ინფორმაცია',
        unknown_user: 'უცნობი მომხმარებელი',
        active_on_campus: 'აქტიურია კამპუსში',
        send_message: 'შეტყობინების გაგზავნა',
        message_seller: 'მიწერე გამყიდველს',
        user_looking_for: 'მომხმარებელი ეძებს...',
        just_now: 'ახლახან',
        minute_ago: '{{count}}წთ წინ',
        hour_ago: '{{count}}სთ წინ',
        day_ago: '{{count}} დღე წინ',
        yesterday: 'გუშინ',
        reply: 'პასუხი',
        replies: 'პასუხები',
        help_out: 'დაეხმარე',
        replying_to: 'პასუხობ',
        write_comment_placeholder: 'დაწერე კომენტარი…',
        new_message: 'ახალი შეტყობინება',
        you_received_a_new_message: 'ახალი შეტყობინება მიიღე',
        group_chat: 'ჯგუფური ჩატი',
        activity_header: 'აქტივობა',
        all_caught_up_activity: 'ყველაფერი ნანახია',
        activity_empty_sub: 'მნიშვნელოვანი განახლებები და აქტივობები აქ გამოჩნდება.',
        cancel_label: 'გაუქმება',
        cancel_request: 'მოთხოვნის გაუქმება',
        send_to_friends: 'გაგზავნა მეგობრებთან',
        search_friends: 'მეგობრების ძებნა…',
        sent: 'გაგზავნილია',
        send: 'გაგზავნა',
        no_friends_found: 'მეგობრები ვერ მოიძებნა',
        no_messages_yet: 'შეტყობინებები ჯერ არ არის',
        you_shared_post: 'შენ გააზიარე ეს პოსტი',
        someone_shared_post: '{{name}}-მა გააზიარა ეს პოსტი',
        video_label: 'ვიდეო',
        photo_label: 'ფოტო',
        user_fallback: 'მომხმარებელი',
        group_fallback: 'ჯგუფი',
        conversation_options: 'საუბრის პარამეტრები',
        clear_history: 'ისტორიის გასუფთავება',
        private_label: 'დახურული',
        join_required_title: 'საჭიროა შეერთება',
        join_required_body: 'შინაარსის სანახავად შეუერთდი თემს.',
        request_sent_title: 'მოთხოვნა გაგზავნილია',
        request_sent_body: 'ადმინი განიხილავს თქვენს თხოვნას.',
        leave_community_title: 'თემიდან გასვლა',
        leave_community_body: 'დარწმუნებული ხარ, რომ გინდა დატოვო თემი?',
        retract_request_title: 'მოთხოვნის გაუქმება',
        retract_request_body: 'დარწმუნებული ხარ, რომ გინდა გააუქმო მოთხოვნა?',
        members_only: 'მხოლოდ წევრები',
        join_to_chat: 'ჩატისთვის შეერთდი',
        enter_chat_room: 'ჩატში შესვლა',
        post_something: 'რაღაც გამოაქვეყნე',
        admin_creator: 'ადმინისტრატორი',
        students_label: 'სტუდენტი',
        manage: 'მართვა',
        locked_body: 'შეუერთდი თემს, რომ ნახო კონტენტი. კონფიდენციალურობისთვის დაფარულია.',
        share: 'გაზიარება',
        launch: 'გაშვება',
        new_label: 'ახალი',
        header_new: 'ახალი',
        header_edit: 'რედაქტირება',
        mini_community: 'მინი საზოგადოება',
        listing_label: 'განცხადება',
        post_placeholder: 'რას ფიქრობ?',
        library_label: 'ბიბლიოთეკა',
        camera_label: 'კამერა',
        add_event_banner: 'დაამატე ბანერი',
        ask_label: 'კითხვა',
        core_problem_placeholder: 'რა არის ძირითადი პრობლემა?',
        stuck_placeholder: 'აუხსენი სად გაიჭედე...',
        add_option_label: 'ვარიანტის დამატება',
        poll_question_placeholder: 'დასვი კითხვა...',
        item_details_label: 'ნივთის დეტალები',
        what_selling_placeholder: 'რას ყიდი?',
        what_looking_placeholder: 'რას ეძებ?',
        tell_more_placeholder: 'გვიამბე მეტი ნივთის შესახებ...',
        post_listing_label: 'გამოქვეყნება',
        posting_to_label: 'პოსტვა',
        when_label: 'როდის',
        where_label: 'სად',
        venue_placeholder: 'ადგილი ან ლინკი',
        tell_event_more_placeholder: 'გვიამბე მეტი ღონისძიებაზე...',
        change_cover: 'შეცვალე ფოტო',
        add_event_cover: 'დაამატე გარეკანი',
        job_title: 'სამუშაოს დასახელება',
        budget: 'ბიუჯეტი',
        details: 'დეტალები',
        selling: 'გაყიდვა',
        requesting: 'მოთხოვნა',
        sharing_label: 'ზიარდება',
        subject_label: 'საგანი',
        in_label: 'აქ',
        setting_time: 'დროის დაყენება...',
        job_tab: 'სამუშაოები',
        study_tab: 'სწავლა',
        add_problem_photo: 'დაამატე პრობლემის ფოტო',
        tips_title: 'რჩევები უკეთესი დახმარებისთვის',
        tip_1: 'იყავი კონკრეტული სათაურში.',
        tip_2: 'აჩვენე რა სცადე—ეს სხვებს ეხმარება!',
        tip_3: 'ატვირთე მკაფიო ფოტო, თუ პრობლემა ვიზუალურია.',
        save: 'შენახვა',
        wait: 'მოითმინეთ',
        success: 'წარმატება',
        error: 'შეცდომა',
        cancel_label: 'გაუქმება',
        done_label: 'დასრულება',
        change: 'შეცვლა',
        image_selected: 'ფოტო არჩეულია',
        option_label: 'ვარიანტი',
        category: 'კატეგორია',
        other: 'სხვა',
        today: 'დღეს',
        tomorrow: 'ხვალ',
        mini_community_hint: 'სასწავლო მინი-საზოგადოების დაწყება საშუალებას მისცემს სხვებს შემოუერთდნენ და ითანამშრომლონ სპეციალურ სივრცეში.',
        mini_community_name_placeholder: 'მინი საზოგადოების სახელი (მაგ. ბიო 101 სასწავლო ოთახი)',
        schedule_goal_placeholder: 'განრიგის მიზანი (მაგ. მხოლოდ შაბათ-კვირა)',
        group_purpose_placeholder: 'რისთვის არის ეს ჯგუფი?',
        fill_all_fields: 'გთხოვთ შეავსოთ ყველა ველი',
        question_posted_success: 'კითხვა გამოქვეყნდა! წარმატებები!',
        posting_failed: 'გამოქვეყნებისას რაღაც შეცდა',
        community_banner: 'თემის ბანერი',
        community_name: 'სახელი',
        community_type: 'ტიპი',
        privacy: 'კონფიდენციალურობა',
        course: 'კურსი',
        interest: 'ინტერესი',
        club: 'კლუბი',
        study_group: 'სასწავლო ჯგუფი',
        private_community: 'დახურული თემი',
        public_community: 'საჯარო თემი',
        private_desc: 'მხოლოდ წევრებს შეუძლიათ პოსტების ნახვა. საჭიროა ადმინის დასტური.',
        public_desc: 'ყველას შეუძლია პოსტების ნახვა და თავისუფლად შემოერთება.',
        add_cover_photo: 'დაამატე გარეკანი (გამოჩნდება თემის პროფილზე)',
        new_community_header: 'ახალი თემი',
        schedule_event_header: 'დაგეგმე ღონისძიება',
        messages_header: 'შეტყობინებები',
        chat_header: 'ჩატი',
        study_discussion_header: 'სასწავლო დისკუსია',
        share_pov_header: 'გააზიარე POV',
        books: 'წიგნები',
        clothes: 'ტანსაცმელი',
        accessories: 'აქსესუარები',
        free: 'უფასო',
        choose_community: 'აირჩიე თემი',
        title_label: 'სათაური',
        post_tab: 'პოსტი',
        poll_tab: 'გამოკითხვა',
        event_tab: 'ღონისძიებები',
        market_tab: 'ბაზარი',
        upload_failed: 'ატვირთვა ვერ მოხერხდა',
        description_label: 'აღწერა',
        location_label: 'მდებარეობა',
        price_label: 'ფასი',
        event_placeholder: 'რა ღონისძიებაა?',
        interested_label: 'მაინტერესებს',
        person_interested: 'დაინტერესებული პირი',
        people_interested: 'დაინტერესებული პირი',
        connect_label: 'დაკავშირება',
        message_label: 'შეტყობინება',
        share_profile_label: 'პროფილის გაზიარება',
        campus_rank_label: 'კამპუსის რანგი',
        no_content_yet: 'კონტენტი ჯერ არ არის',
        subject_math: 'მათემატიკა',
        subject_science: 'მეცნიერება',
        subject_english: 'ინგლისური',
        subject_history: 'ისტორია',
        subject_physics: 'ფიზიკა',
        subject_cs: 'კომპიუტერული მეცნიერება',
        subject_business: 'ბიზნესი',
        subject_arts: 'ხელოვნება',
        subject_other: 'სხვა',
        profile_location: 'მდებარეობა',
        profile_birthday: 'დაბადების დღე',
        profile_relationship: 'ურთიერთობის სტატუსი',
        profile_class_of: 'კლასი',
        profile_graduated: 'დამთავრებული',
        profile_not_graduated: 'ჯერ არ დამთავრებულა',
        profile_vats: 'Vats',
        notif_all_caught_up: 'ყველაფერი ნანახია',
        notif_updates_here: 'მნიშვნელოვანი განახლებები აქ გამოჩნდება',
        notif_now: 'ახლა',
        time_m: 'წთ',
        time_h: 'სთ',
        time_d: 'დ',
        time_ago: 'წინ',
        system_only_message: 'ეს მხოლოდ სისტემური ანგარიშია. ამ შეტყობინებას ვერ უპასუხებთ.',
        system_account: 'სისტემური ანგარიში',
        chat_message_placeholder: 'შეტყობინება...',
        chat_reply: 'პასუხი',
        chat_copy: 'კოპირება',
        chat_delete: 'წაშლა',
        chat_typing: 'წერს...',
        online: 'ონლაინ',
        offline: 'ოფლაინ',
        edited_label: 'შესწორებული',
        'New Poll Vote': 'ახალი გამოკითხვის ხმა',
        'New Join Request': 'ახალი გაწევრიანების მოთხოვნა',
        'New Homework Help Answer!': 'ახალი დავალების პასუხი!',
        'New Reply': 'ახალი პასუხი',
        'New Upvote': 'ახალი მოწონება',
        'New Post from Friend': 'მეგობრის ახალი პოსტი',
        'New Friend Request': 'ახალი მეგობრობის მოთხოვნა',
        'New in ': 'ახალი: ',
        'rel_private': 'პირადი',
        'rel_single': 'მარტოხელა',
        'rel_in_relationship': 'ურთიერთობაში',
        'rel_married': 'დაქორწინებული',
        'rel_complicated': 'რთულია',
    }
};

export type TranslationKey = keyof typeof translations['en'];

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof typeof translations['en']) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const loadLanguage = async () => {
            const saved = await AsyncStorage.getItem('user_language');
            if (saved && (saved === 'en' || saved === 'tr' || saved === 'ka')) {
                setLanguageState(saved as Language);
            }
        };
        loadLanguage();
    }, []);

    const setLanguage = async (lang: Language) => {
        setLanguageState(lang);
        await AsyncStorage.setItem('user_language', lang);
    };

    const t = (key: keyof typeof translations['en']): string => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
