import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'tr' | 'ka';

const translations = {
    en: {
        welcome: 'Welcome Back',
        login_subtitle: 'Log in to access your campus network.',
        email: 'Email',
        password: 'Password',
        forgot_password: 'Forgot password?',
        login: 'Log In',
        no_account: "Don't have an account? ",
        apply_access: 'Apply for access',
        create_account: 'Create Account',
        register_subtitle: 'Join your campus community and stay connected.',
        full_name: 'Full Name',
        already_account: 'Already have an account? ',
        login_now: 'Log in',
        home: 'Home',
        profile: 'Profile',
        notifications: 'Notifications',
        friends: 'Friends',
        settings: 'Settings',
        logout: 'Log out',
        delete_account: 'Delete account',
        posts: 'Posts',
        events: 'Events',
        polls: 'Polls',
        listings: 'Listings',
        search: 'Search',
        connect: 'Connect',
        message: 'Message',
        edit_profile: 'Edit Profile',
        share_profile: 'Share profile',
        complete_profile: 'Complete your profile to stand out!',
        bio_placeholder: 'Add a bio to tell students about yourself',
        campus_pioneer: 'Campus Pioneer Rank',
        loading: 'Loading...',
        feed: 'Feed',
        explore: 'Explore',
        marketplace: 'Marketplace',
        study: 'Study',
        create: 'Create',
        new_post: 'New Post',
        share_with_campus: 'Share with your campus',
        new_event: 'New Event',
        organize_activities: 'Organize campus activities',
        sell_request: 'Sell or Request Item',
        list_on_market: 'List on marketplace',
        ask_question: 'Ask Question',
        get_homework_help: 'Get homework help',
        community_hub: 'Community Hub',
        search_communities_placeholder: 'Search communities...',
        search_students_placeholder: 'Search by name or dept',
        communities_tab: 'Communities',
        students_tab: 'Students',
        members_count: 'members',
        friends_label: 'Friends',
        requested_label: 'Requested',
        add_friend_label: 'Add Friend',
        discover_communities: 'Discover & join communities',
        start_new_community: 'Start New Community',
        no_communities_yet: 'No communities yet',
        be_the_first: 'Be the first to start one!',
        no_students_found: 'No students found',
        try_different_search: 'Try a different search term',
        all_listings: 'All Listings',
        for_sale: 'For Sale',
        requests_tab: 'Requests',
        items_count: 'Items',
        all_communities: 'All Communities',
        filter_by_community: 'Filter by Community',
        request_badge: 'REQUEST',
        free_badge: 'FREE',
        new_badge: 'NEW',
        looking_for: 'is looking for',
        untitled_item: 'Untitled Item',
        no_requests_yet: 'No requests here yet',
        no_items_for_sale: 'No items for sale yet',
        nothing_here_yet: 'Nothing here yet',
        be_the_first_to_request: 'Be the first to request something!',
        be_the_first_to_list: 'Be the first to list something!',
        be_the_first_to_both: 'Be the first to list or request something!',
        request_an_item: 'Request an Item',
        sell_an_item: 'Sell an Item',
        create_a_listing: 'Create a Listing',
        all_subjects: 'All',
        no_questions_in: 'No questions in',
        be_the_first_to_ask: 'Be the first to ask or help out!',
        search_messages_placeholder: 'Search messages...',
        no_conversations: 'No conversations',
        start_chatting_sub: 'Start chatting with community members',
        profile_not_found: 'User profile not found',
        user_blocked: 'User Blocked',
        profile_unavailable: 'Profile Unavailable',
        block_desc_me: 'You have blocked this user. Unblock them to interact.',
        block_desc_other: 'You cannot view this user content.',
        unblock_label: 'Unblock',
        connect_label: 'Connect',
        message_label: 'Message',
        share_profile_label: 'Share Profile',
        no_content_yet: 'No content here yet',
        campus_rank_label: 'Campus Pioneer Rank',
        score_label: 'Score',
        post_tab: 'Posts',
        event_tab: 'Events',
        poll_tab: 'Polls',
        market_tab: 'Market',
        math: 'Mathematics',
        science: 'Science',
        english: 'English',
        history: 'History',
        physics: 'Physics',
        cs: 'Comp Sci',
        business: 'Business',
        arts: 'Arts',
        other: 'Other',
        new_community_header: 'New Community',
        messages_header: 'Messages',
        chat_header: 'Chat',
        study_discussion_header: 'Study Discussion',
        ask_for_help_header: 'Ask for Help',
        schedule_event_header: 'Schedule Event',
        share_pov_header: 'Share Your POV',
        language: 'Language',
        lang_en: 'English',
        lang_tr: 'Turkish',
        lang_ka: 'Georgian',
    },
    tr: {
        welcome: 'Tekrar Hoş Geldiniz',
        login_subtitle: 'Kampüs ağına erişmek için giriş yapın.',
        email: 'E-posta',
        password: 'Şifre',
        forgot_password: 'Şifremi unuttum?',
        login: 'Giriş Yap',
        no_account: 'Hesabınız yok mu? ',
        apply_access: 'Erişim için başvur',
        create_account: 'Hesap Oluştur',
        register_subtitle: 'Kampüs topluluğunuza katılın ve bağlantıda kalın.',
        full_name: 'Ad Soyad',
        already_account: 'Zaten bir hesabınız var mı? ',
        login_now: 'Giriş yap',
        home: 'Ana Sayfa',
        profile: 'Profil',
        notifications: 'Bildirimler',
        friends: 'Arkadaşlar',
        settings: 'Ayarlar',
        logout: 'Çıkış yap',
        delete_account: 'Hesabı sil',
        posts: 'Gönderiler',
        events: 'Etkinlikler',
        polls: 'Anketler',
        listings: 'İlanlar',
        search: 'Ara',
        connect: 'Bağlan',
        message: 'Mesaj',
        edit_profile: 'Profili Düzenle',
        share_profile: 'Profili Paylaş',
        complete_profile: 'Öne çıkmak için profilini tamamla!',
        bio_placeholder: 'Öğrencilere kendinden bahsetmek için bir biyografi ekle',
        campus_pioneer: 'Kampüs Öncü Sıralaması',
        loading: 'Yükleniyor...',
        feed: 'Akış',
        explore: 'Keşfet',
        marketplace: 'Pazar Yeri',
        study: 'Ders Çalış',
        create: 'Oluştur',
        new_post: 'Yeni Gönderi',
        share_with_campus: 'Kampüsünle paylaş',
        new_event: 'Yeni Etkinlik',
        organize_activities: 'Kampüs etkinlikleri düzenle',
        sell_request: 'Sat veya İstek Yap',
        list_on_market: 'Pazarda listele',
        ask_question: 'Soru Sor',
        get_homework_help: 'Ödev yardımı al',
        community_hub: 'Topluluk Merkezi',
        search_communities_placeholder: 'Topluluk ara...',
        search_students_placeholder: 'İsim veya bölümle ara',
        communities_tab: 'Topluluklar',
        students_tab: 'Öğrenciler',
        members_count: 'üye',
        friends_label: 'Arkadaşlar',
        requested_label: 'İstek Gönderildi',
        add_friend_label: 'Arkadaş Ekle',
        discover_communities: 'Toplulukları keşfet ve katıl',
        start_new_community: 'Yeni Topluluk Başlat',
        no_communities_yet: 'Henüz topluluk yok',
        be_the_first: 'İlk başlatan sen ol!',
        no_students_found: 'Öğrenci bulunamadı',
        try_different_search: 'Farklı bir arama terimi dene',
        all_listings: 'Tüm İlanlar',
        for_sale: 'Satılık',
        requests_tab: 'İstekler',
        items_count: 'Ürün',
        all_communities: 'Tüm Topluluklar',
        filter_by_community: 'Topluluğa Göre Filtrele',
        request_badge: 'İSTEK',
        free_badge: 'ÜCRETSİZ',
        new_badge: 'YENİ',
        looking_for: 'arıyor',
        untitled_item: 'Başlıksız Ürün',
        no_requests_yet: 'Henüz istek yok',
        no_items_for_sale: 'Henüz satılık ürün yok',
        nothing_here_yet: 'Burada henüz bir şey yok',
        be_the_first_to_request: 'İlk istek yapan sen ol!',
        be_the_first_to_list: 'İlk ilan veren sen ol!',
        be_the_first_to_both: 'İlk ilan veren veya istek yapan sen ol!',
        request_an_item: 'Ürün İste',
        sell_an_item: 'Ürün Sat',
        create_a_listing: 'İlan Oluştur',
        all_subjects: 'Hepsi',
        no_questions_in: 'Soru yok:',
        be_the_first_to_ask: 'İlk soran veya yardım eden sen ol!',
        search_messages_placeholder: 'Mesajlarda ara...',
        no_conversations: 'Sohbet yok',
        start_chatting_sub: 'Topluluk üyeleriyle sohbete başla',
        profile_not_found: 'Kullanıcı profili bulunamadı',
        user_blocked: 'Kullanıcı Engellendi',
        profile_unavailable: 'Profil Kullanılamıyor',
        block_desc_me: 'Bu kullanıcıyı engelledin. Etkileşim için engeli kaldır.',
        block_desc_other: 'Bu kullanıcı içeriğini görüntüleyemezsin.',
        unblock_label: 'Engeli Kaldır',
        connect_label: 'Bağlan',
        message_label: 'Mesaj',
        share_profile_label: 'Profili Paylaş',
        no_content_yet: 'Henüz içerik yok',
        campus_rank_label: 'Kampüs Öncü Sıralaması',
        score_label: 'Puan',
        post_tab: 'Gönderiler',
        event_tab: 'Etkinlikler',
        poll_tab: 'Anketler',
        market_tab: 'Pazar',
        math: 'Matematik',
        science: 'Fen Bilimleri',
        english: 'İngilizce',
        history: 'Tarih',
        physics: 'Fizik',
        cs: 'Bilgisayar Bilimi',
        business: 'İşletme',
        arts: 'Sanat',
        other: 'Diğer',
        new_community_header: 'Yeni Topluluk',
        messages_header: 'Mesajlar',
        chat_header: 'Sohbet',
        study_discussion_header: 'Ders Tartışması',
        ask_for_help_header: 'Yardım İste',
        schedule_event_header: 'Etkinlik Planla',
        share_pov_header: 'POV Paylaş',
        language: 'Dil',
        lang_en: 'İngilizce',
        lang_tr: 'Türkçe',
        lang_ka: 'Gürcüce',
    },
    ka: {
        welcome: 'მოგესალმებით',
        login_subtitle: 'შედით სისტემაში თქვენს კამპუსურ ქსელზე წვდომისთვის.',
        email: 'ელ-ფოსტა',
        password: 'პაროლი',
        forgot_password: 'დაგავიწყდათ პაროლი?',
        login: 'შესვლა',
        no_account: 'არ გაქვთ ანგარიში? ',
        apply_access: 'მოითხოვეთ წვდომა',
        create_account: 'ანგარიშის შექმნა',
        register_subtitle: 'შეუერთდით თქვენს კამპუსურ საზოგადოებას.',
        full_name: 'სრული სახელი',
        already_account: 'უკვე გაქვთ ანგარიში? ',
        login_now: 'შესვლა',
        home: 'მთავარი',
        profile: 'პროფილი',
        notifications: 'შეტყობინებები',
        friends: 'მეგობრები',
        settings: 'პარამეტრები',
        logout: 'გასვლა',
        delete_account: 'ანგარიშის წაშლა',
        posts: 'პოსტები',
        events: 'ღონისძიებები',
        polls: 'გამოკითხვები',
        listings: 'განცხადებები',
        search: 'ძებნა',
        connect: 'დაკავშირება',
        message: 'შეტყობინება',
        edit_profile: 'პროფილის რედაქტირება',
        share_profile: 'პროფილის გაზიარება',
        complete_profile: 'შეავსეთ პროფილი გამოსაჩენად!',
        bio_placeholder: 'დაამატეთ ბიოგრაფია თქვენს შესახებ',
        campus_pioneer: 'კამპუსის პიონერის რანგი',
        loading: 'იტვირთება...',
        feed: 'არხი',
        explore: 'აღმოაჩინე',
        marketplace: 'მარკეტი',
        study: 'სწავლა',
        create: 'შექმნა',
        new_post: 'ახალი პოსტი',
        share_with_campus: 'გაუზიარე კამპუსს',
        new_event: 'ახალი ღონისძიება',
        organize_activities: 'დაგეგმე აქტივობები',
        sell_request: 'გაყიდე ან მოითხოვე',
        list_on_market: 'დაამატე მარკეტში',
        ask_question: 'კითხვის დასმა',
        get_homework_help: 'დახმარება დავალებაში',
        community_hub: 'საზოგადოება',
        search_communities_placeholder: 'მოძებნე თემები...',
        search_students_placeholder: 'სახელით ან დეპარტამენტით',
        communities_tab: 'თემები',
        students_tab: 'სტუდენტები',
        members_count: 'წევრი',
        friends_label: 'მეგობრები',
        requested_label: 'მოთხოვნილია',
        add_friend_label: 'დამატება',
        discover_communities: 'აღმოაჩინე და შეუერთდი',
        start_new_community: 'ახალი თემის შექმნა',
        no_communities_yet: 'თემები არ არის',
        be_the_first: 'იყავი პირველი!',
        no_students_found: 'სტუდენტები ვერ მოიძებნა',
        try_different_search: 'სცადე სხვა სიტყვა',
        all_listings: 'ყველა განცხადება',
        for_sale: 'იყიდება',
        requests_tab: 'მოთხოვნები',
        items_count: 'ნივთი',
        all_communities: 'ყველა თემი',
        filter_by_community: 'გაფილტრე თემით',
        request_badge: 'მოთხოვნა',
        free_badge: 'უფასო',
        new_badge: 'ახალი',
        looking_for: 'ეძებს',
        untitled_item: 'უსახელო ნივთი',
        no_requests_yet: 'მოთხოვნები არ არის',
        no_items_for_sale: 'განცხადებები არ არის',
        nothing_here_yet: 'აქ არაფერია',
        be_the_first_to_request: 'იყავი პირველი ვინც მოითხოვს!',
        be_the_first_to_list: 'იყავი პირველი ვინც დადებს!',
        be_the_first_to_both: 'იყავი პირველი ვინც დადებს!',
        request_an_item: 'ითხოვე ნივთი',
        sell_an_item: 'გაყიდე ნივთი',
        create_a_listing: 'დადე განცხადება',
        all_subjects: 'ყველა',
        no_questions_in: 'კითხვები არ არის:',
        be_the_first_to_ask: 'იყავი პირველი ვინც იკითხავს!',
        search_messages_placeholder: 'მოძებნე შეტყობინებები...',
        no_conversations: 'საუბრები არ არის',
        start_chatting_sub: 'დაიწყე მიმოწერა წევრებთან',
        profile_not_found: 'პროფილი ვერ მოიძებნა',
        user_blocked: 'დაბლოკილია',
        profile_unavailable: 'პროფილი მიუწვდომელია',
        block_desc_me: 'თქვენ დაბლოკეთ ეს მომხმარებელი.',
        block_desc_other: 'თქვენ ვერ ხედავთ ამ მომხმარებელს.',
        unblock_label: 'განბლოკვა',
        connect_label: 'დამატება',
        message_label: 'მიწერა',
        share_profile_label: 'გაზიარება',
        no_content_yet: 'კონტენტი არ არის',
        campus_rank_label: 'კამპუსის პიონერის რანგი',
        score_label: 'ქულა',
        post_tab: 'პოსტები',
        event_tab: 'ღონისძიებები',
        poll_tab: 'გამოკითხვები',
        market_tab: 'მარკეტი',
        math: 'მათემატიკა',
        science: 'მეცნიერება',
        english: 'ინგლისური',
        history: 'ისტორია',
        physics: 'ფიზიკა',
        cs: 'კომპ. მეცნიერება',
        business: 'ბიზნესი',
        arts: 'ხელოვნება',
        other: 'სხვა',
        new_community_header: 'ახალი თემი',
        messages_header: 'შეტყობინებები',
        chat_header: 'ჩატი',
        study_discussion_header: 'სწავლის განხილვა',
        ask_for_help_header: 'ითხოვე დახმარება',
        schedule_event_header: 'დაგეგმე ღონისძიება',
        share_pov_header: 'გააზიარე POV',
        language: 'ენა',
        lang_en: 'ინგლისური',
        lang_tr: 'თურქული',
        lang_ka: 'ქართული',
    }
};

export type TranslationKey = keyof typeof translations['en'];

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof typeof translations['en']) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const loadLanguage = async () => {
            const saved = await AsyncStorage.getItem('user_language');
            if (saved && (saved === 'en' || saved === 'tr' || saved === 'ka')) {
                setLanguageState(saved as Language);
            }
        };
        loadLanguage();
    }, []);

    const setLanguage = async (lang: Language) => {
        setLanguageState(lang);
        await AsyncStorage.setItem('user_language', lang);
    };

    const t = (key: keyof typeof translations['en']): string => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
