import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'tr' | 'ka';

const translations = {
    en: {
        welcome: 'Welcome Back',
        login_subtitle: 'Log in to access your campus network.',
        email: 'Email',
        password: 'Password',
        forgot_password: 'Forgot password?',
        login: 'Log In',
        no_account: "Don't have an account? ",
        apply_access: 'Apply for access',
        create_account: 'Create Account',
        register_subtitle: 'Join your campus community and stay connected.',
        full_name: 'Full Name',
        already_account: 'Already have an account? ',
        login_now: 'Log in',
        home: 'Home',
        profile: 'Profile',
        notifications: 'Notifications',
        friends: 'Friends',
        settings: 'Settings',
        logout: 'Log out',
        delete_account: 'Delete account',
        posts: 'Posts',
        events: 'Events',
        polls: 'Polls',
        listings: 'Listings',
        search: 'Search',
        connect: 'Connect',
        message: 'Message',
        edit_profile: 'Edit Profile',
        share_profile: 'Share profile',
        complete_profile: 'Complete your profile to stand out!',
        bio_placeholder: 'Add a bio to tell students about yourself',
        campus_pioneer: 'Campus Pioneer Rank',
        loading: 'Loading...',
        feed: 'Feed',
        explore: 'Explore',
        marketplace: 'Marketplace',
        study: 'Study',
        create: 'Create',
        new_post: 'New Post',
        share_with_campus: 'Share with your campus',
        new_event: 'New Event',
        organize_activities: 'Organize campus activities',
        sell_request: 'Sell or Request Item',
        list_on_market: 'List on marketplace',
        ask_question: 'Ask Question',
        get_homework_help: 'Get homework help',
        community_hub: 'Community Hub',
        search_communities_placeholder: 'Search communities...',
        search_students_placeholder: 'Search by name or dept',
        communities_tab: 'Communities',
        students_tab: 'Students',
        members_count: 'members',
        friends_label: 'Friends',
        requested_label: 'Requested',
        add_friend_label: 'Add Friend',
        discover_communities: 'Discover & join communities',
        start_new_community: 'Start New Community',
        no_communities_yet: 'No communities yet',
        be_the_first: 'Be the first to start one!',
        no_students_found: 'No students found',
        try_different_search: 'Try a different search term',
        all_listings: 'All Listings',
        for_sale: 'For Sale',
        requests_tab: 'Requests',
        items_count: 'Items',
        all_communities: 'All Communities',
        filter_by_community: 'Filter by Community',
        request_badge: 'REQUEST',
        free_badge: 'FREE',
        new_badge: 'NEW',
        looking_for: 'is looking for',
        untitled_item: 'Untitled Item',
        no_requests_yet: 'No requests here yet',
        no_items_for_sale: 'No items for sale yet',
        nothing_here_yet: 'Nothing here yet',
        be_the_first_to_request: 'Be the first to request something!',
        be_the_first_to_list: 'Be the first to list something!',
        be_the_first_to_both: 'Be the first to list or request something!',
        request_an_item: 'Request an Item',
        sell_an_item: 'Sell an Item',
        create_a_listing: 'Create a Listing',
        all_subjects: 'All',
        no_questions_in: 'No questions in',
        be_the_first_to_ask: 'Be the first to ask or help out!',
        search_messages_placeholder: 'Search messages...',
        no_conversations: 'No conversations',
        start_chatting_sub: 'Start chatting with community members',
        profile_not_found: 'User profile not found',
        user_blocked: 'User Blocked',
        profile_unavailable: 'Profile Unavailable',
        block_desc_me: 'You have blocked this user. Unblock them to interact.',
        block_desc_other: 'You cannot view this user content.',
        unblock_label: 'Unblock',
        connect_label: 'Connect',
        message_label: 'Message',
        share_profile_label: 'Share Profile',
        no_content_yet: 'No content here yet',
        campus_rank_label: 'Campus Pioneer Rank',
        score_label: 'Score',
        post_tab: 'Posts',
        event_tab: 'Events',
        poll_tab: 'Polls',
        market_tab: 'Market',
        reply: 'Reply',
        replies: 'Replies',
        help_out: 'Help out',
        replying_to: 'Replying to',
        write_comment_placeholder: 'Write a comment…',
        activity_header: 'Activity',
        all_caught_up_activity: 'All caught up',
        activity_empty_sub: 'We will notify you about important updates here',
        cancel_request: 'Cancel Request',
        send_to_friends: 'Send to Friends',
        search_friends: 'Search friends…',
        sent: 'Sent',
        send: 'Send',
        no_friends_found: 'No friends found',
        no_messages_yet: 'No messages yet',
        you_shared_post: 'You shared this post',
        someone_shared_post: '{{name}} shared this post',
        video_label: 'Video',
        photo_label: 'Photo',
        user_fallback: 'User',
        group_fallback: 'Group',
        conversation_options: 'Conversation Options',
        clear_history: 'Clear History',
        private_label: 'PRIVATE',
        join_required_title: 'Join Required',
        join_required_body: 'You need to be a member to see this content.',
        request_sent_title: 'Request Sent',
        request_sent_body: 'An admin will review your request.',
        leave_community_title: 'Leave Community',
        leave_community_body: 'Are you sure you want to leave this community?',
        retract_request_title: 'Retract Request',
        retract_request_body: 'Are you sure you want to retract your join request?',
        members_only: 'Members Only',
        join_to_chat: 'Join to Chat',
        enter_chat_room: 'Enter Chat Room',
        post_something: 'Post Something',
        admin_creator: 'CREATOR ADMIN',
        students_label: 'Students',
        manage: 'Manage',
        locked_body: 'Join this community to see its feed and connect with students. Content is hidden to protect privacy.',
        math: 'Mathematics',
        science: 'Science',
        english: 'English',
        history: 'History',
        physics: 'Physics',
        cs: 'Comp Sci',
        business: 'Business',
        arts: 'Arts',
        other: 'Other',
        new_community_header: 'New Community',
        messages_header: 'Messages',
        chat_header: 'Chat',
        study_discussion_header: 'Study Discussion',
        ask_for_help_header: 'Ask for Help',
        schedule_event_header: 'Schedule Event',
        share_pov_header: 'Share Your POV',
        language: 'Language',
        lang_en: 'English',
        lang_tr: 'Turkish',
        lang_ka: 'Georgian',
        // Marketplace & categories
        books: 'Books',
        clothes: 'Clothes',
        accessories: 'Accessories',
        feed_tab: 'Feed',
        events_tab: 'Events',
        market_tab_label: 'Market',
        list_view: 'List',
        calendar_view: 'Calendar',
        community_not_found: 'Community not found',
        private_community_title: 'Private Community',
        private_community_body: 'Join this community to see its feed and connect with students. Content is hidden to protect privacy.',
        request_to_join: 'Request to Join',
        cancel_request: 'Cancel Request',
        empty_events: 'No upcoming events posted.',
        empty_market: 'The marketplace is empty.',
        empty_feed: 'Be the first to share something here!',
        enter_chat_room: 'Enter Chat Room',
        members_only: 'Members Only',
        join_to_chat: 'Join to Chat',
        post_something: 'Post Something',
        member_status_member: 'Member',
        member_status_pending: 'Requested',
        member_status_request: 'Request',
        member_status_join: 'Join Hub',
        admin_creator: 'CREATOR ADMIN',
        study_hub: 'STUDY HUB',
        private_label: 'PRIVATE',
        students_label: 'Students',
        manage: 'Manage',
        join_required_title: 'Join Required',
        join_required_body: 'You need to be a member to enter this chat.',
        chat_initializing_title: 'Chat Initializing',
        chat_initializing_body: 'The chat room is being synchronized. Please try again in a few seconds.',
        retract_request_title: 'Retract Request',
        retract_request_body: 'Are you sure you want to retract your join request for this community?',
        leave_community_title: 'Leave Community',
        leave_community_body: 'Are you sure you want to leave this community?',
        request_sent_title: 'Request Sent',
        request_sent_body: 'This community is private. An admin will review your request.',
        pulse_title: 'The Pulse',
        pulse_rules_title: 'Pulse Rules',
        pulse_rules_body: 'No bullying, no names, no harassment. Keep the campus safe.',
        pulse_empty_title: 'The Pulse is empty',
        pulse_empty_sub: 'Be the first to speak your mind anonymously.',
        pulse_empty_cta: 'Ignite The Pulse',
        // Edit profile
        save: 'Save',
        change_profile_picture: 'Change Profile Picture',
        display_name: 'Display Name',
        username_label: 'Username',
        personal_details: 'Personal Details (Optional)',
        hometown: 'Hometown',
        age: 'Age',
        relationship_status: 'Relationship Status',
        select_status: 'Select Status',
        show_hometown: 'Show Hometown',
        show_age: 'Show Age',
        show_relationship: 'Show Relationship',
        academic_details: 'Academic Details',
        department_label: 'Department / Major',
        select_department: 'Select Department',
        graduation_year_label: 'Graduation Year / Level',
        select_year: 'Select Year/Level',
        show_department: 'Show Department',
        show_year: 'Show Class/Year',
        show_rank: 'Show Pioneer Rank',
        success: 'Success',
        profile_updated: 'Profile updated successfully!',
        error: 'Error',
        name_required: 'Name is required',
        upload_failed: 'Upload Failed',
        clear: 'Clear',
        friend_requests: 'Friend Requests',
        notifications_label: 'Notifications',
        theme: 'Theme',
        privacy_policy: 'Privacy Policy',
        terms_of_use: 'Terms of Use',
        privacy_desc: 'How we protect your campus data',
        terms_desc: 'The rules of our student community',
        logout_label: 'Log out',
        delete_account_label: 'Delete account',
        no_items_yet: 'No items yet',
        score: 'Score',
        pulse_rules_prefix: 'Pulse Rules:',
        listed: 'Listed',
        just_now: 'Just now',
        minute_ago: '{{count}}m ago',
        hour_ago: '{{count}}h ago',
        day_ago: '{{count}} days ago',
        yesterday: 'Yesterday',
        listed: 'Listed',
    },
    tr: {
        welcome: 'Tekrar Hoş Geldiniz',
        login_subtitle: 'Kampüs ağına erişmek için giriş yapın.',
        email: 'E-posta',
        password: 'Şifre',
        forgot_password: 'Şifremi unuttum?',
        login: 'Giriş Yap',
        no_account: 'Hesabınız yok mu? ',
        apply_access: 'Erişim için başvur',
        create_account: 'Hesap Oluştur',
        register_subtitle: 'Kampüs topluluğunuza katılın ve bağlantıda kalın.',
        full_name: 'Ad Soyad',
        already_account: 'Zaten bir hesabınız var mı? ',
        login_now: 'Giriş yap',
        home: 'Ana Sayfa',
        profile: 'Profil',
        notifications: 'Bildirimler',
        friends: 'Arkadaşlar',
        settings: 'Ayarlar',
        logout: 'Çıkış yap',
        delete_account: 'Hesabı sil',
        posts: 'Gönderiler',
        events: 'Etkinlikler',
        polls: 'Anketler',
        listings: 'İlanlar',
        search: 'Ara',
        connect: 'Bağlan',
        message: 'Mesaj',
        edit_profile: 'Profili Düzenle',
        share_profile: 'Profili Paylaş',
        complete_profile: 'Öne çıkmak için profilini tamamla!',
        bio_placeholder: 'Öğrencilere kendinden bahsetmek için bir biyografi ekle',
        campus_pioneer: 'Kampüs Öncü Sıralaması',
        loading: 'Yükleniyor...',
        feed: 'Akış',
        explore: 'Keşfet',
        marketplace: 'Pazar Yeri',
        study: 'Ders Çalış',
        create: 'Oluştur',
        new_post: 'Yeni Gönderi',
        share_with_campus: 'Kampüsünle paylaş',
        new_event: 'Yeni Etkinlik',
        organize_activities: 'Kampüs etkinlikleri düzenle',
        sell_request: 'Sat veya İstek Yap',
        list_on_market: 'Pazarda listele',
        ask_question: 'Soru Sor',
        get_homework_help: 'Ödev yardımı al',
        community_hub: 'Topluluk Merkezi',
        search_communities_placeholder: 'Topluluk ara...',
        search_students_placeholder: 'İsim veya bölümle ara',
        communities_tab: 'Topluluklar',
        students_tab: 'Öğrenciler',
        members_count: 'üye',
        friends_label: 'Arkadaşlar',
        requested_label: 'İstek Gönderildi',
        add_friend_label: 'Arkadaş Ekle',
        discover_communities: 'Toplulukları keşfet ve katıl',
        start_new_community: 'Yeni Topluluk Başlat',
        no_communities_yet: 'Henüz topluluk yok',
        be_the_first: 'İlk başlatan sen ol!',
        no_students_found: 'Öğrenci bulunamadı',
        try_different_search: 'Farklı bir arama terimi dene',
        all_listings: 'Tüm İlanlar',
        for_sale: 'Satılık',
        requests_tab: 'İstekler',
        items_count: 'Ürün',
        all_communities: 'Tüm Topluluklar',
        filter_by_community: 'Topluluğa Göre Filtrele',
        request_badge: 'İSTEK',
        free_badge: 'ÜCRETSİZ',
        new_badge: 'YENİ',
        looking_for: 'arıyor',
        untitled_item: 'Başlıksız Ürün',
        no_requests_yet: 'Henüz istek yok',
        no_items_for_sale: 'Henüz satılık ürün yok',
        nothing_here_yet: 'Burada henüz bir şey yok',
        be_the_first_to_request: 'İlk istek yapan sen ol!',
        be_the_first_to_list: 'İlk ilan veren sen ol!',
        be_the_first_to_both: 'İlk ilan veren veya istek yapan sen ol!',
        request_an_item: 'Ürün İste',
        sell_an_item: 'Ürün Sat',
        create_a_listing: 'İlan Oluştur',
        all_subjects: 'Hepsi',
        no_questions_in: 'Soru yok:',
        be_the_first_to_ask: 'İlk soran veya yardım eden sen ol!',
        search_messages_placeholder: 'Mesajlarda ara...',
        no_conversations: 'Sohbet yok',
        start_chatting_sub: 'Topluluk üyeleriyle sohbete başla',
        profile_not_found: 'Kullanıcı profili bulunamadı',
        user_blocked: 'Kullanıcı Engellendi',
        profile_unavailable: 'Profil Kullanılamıyor',
        block_desc_me: 'Bu kullanıcıyı engelledin. Etkileşim için engeli kaldır.',
        block_desc_other: 'Bu kullanıcı içeriğini görüntüleyemezsin.',
        unblock_label: 'Engeli Kaldır',
        connect_label: 'Bağlan',
        message_label: 'Mesaj',
        share_profile_label: 'Profili Paylaş',
        no_content_yet: 'Henüz içerik yok',
        campus_rank_label: 'Kampüs Öncü Sıralaması',
        score_label: 'Puan',
        post_tab: 'Gönderiler',
        event_tab: 'Etkinlikler',
        poll_tab: 'Anketler',
        market_tab: 'Pazar',
        math: 'Matematik',
        science: 'Fen Bilimleri',
        english: 'İngilizce',
        history: 'Tarih',
        physics: 'Fizik',
        cs: 'Bilgisayar Bilimi',
        business: 'İşletme',
        arts: 'Sanat',
        other: 'Diğer',
        new_community_header: 'Yeni Topluluk',
        messages_header: 'Mesajlar',
        chat_header: 'Sohbet',
        study_discussion_header: 'Ders Tartışması',
        ask_for_help_header: 'Yardım İste',
        schedule_event_header: 'Etkinlik Planla',
        share_pov_header: 'POV Paylaş',
        language: 'Dil',
        lang_en: 'İngilizce',
        lang_tr: 'Türkçe',
        lang_ka: 'Gürcüce',
        books: 'Kitaplar',
        clothes: 'Kıyafetler',
        accessories: 'Aksesuarlar',
        feed_tab: 'Akış',
        events_tab: 'Etkinlikler',
        market_tab_label: 'Pazar',
        list_view: 'Liste',
        calendar_view: 'Takvim',
        community_not_found: 'Topluluk bulunamadı',
        private_community_title: 'Özel Topluluk',
        private_community_body: 'Akışı görmek için bu topluluğa katılmalısın. İçerik gizlidir.',
        request_to_join: 'Katılma isteği gönder',
        cancel_request: 'İsteği iptal et',
        send_to_friends: 'Arkadaşlara gönder',
        search_friends: 'Arkadaş ara…',
        sent: 'Gönderildi',
        send: 'Gönder',
        no_friends_found: 'Arkadaş bulunamadı',
        empty_events: 'Yaklaşan etkinlik yok.',
        empty_market: 'Pazar boş.',
        empty_feed: 'İlk paylaşımı sen yap!',
        enter_chat_room: 'Sohbete gir',
        members_only: 'Sadece üyeler',
        join_to_chat: 'Sohbet için katıl',
        post_something: 'Bir şey paylaş',
        member_status_member: 'Üye',
        member_status_pending: 'İstek gönderildi',
        member_status_request: 'İstek',
        member_status_join: 'Topluluğa katıl',
        admin_creator: 'KURUCUSU',
        study_hub: 'DERS MERKEZİ',
        private_label: 'GİZLİ',
        students_label: 'Öğrenci',
        manage: 'Yönet',
        join_required_title: 'Katılım gerekli',
        join_required_body: 'Sohbete girmek için üye olmalısın.',
        chat_initializing_title: 'Sohbet hazırlanıyor',
        chat_initializing_body: 'Sohbet odası senkronize ediliyor. Lütfen birkaç saniye sonra tekrar dene.',
        retract_request_title: 'İsteği geri çek',
        retract_request_body: 'Bu topluluk için katılma isteğini geri çekmek istiyor musun?',
        leave_community_title: 'Topluluktan ayrıl',
        leave_community_body: 'Topluluktan ayrılmak istediğine emin misin?',
        request_sent_title: 'İstek gönderildi',
        request_sent_body: 'Bu topluluk gizlidir. Bir yönetici isteğini inceleyecek.',
        pulse_title: 'Pulse',
        pulse_rules_title: 'Pulse Kuralları',
        pulse_rules_body: 'Zorbalık yok, isim yok, taciz yok. Kampüsü güvenli tut.',
        pulse_empty_title: 'Pulse boş',
        pulse_empty_sub: 'Düşünceni anonim olarak ilk sen paylaş.',
        pulse_empty_cta: 'Pulse’u başlat',
        save: 'Kaydet',
        change_profile_picture: 'Profil fotoğrafını değiştir',
        display_name: 'Görünen Ad',
        username_label: 'Kullanıcı adı',
        personal_details: 'Kişisel Bilgiler (Opsiyonel)',
        hometown: 'Memleket',
        age: 'Yaş',
        relationship_status: 'İlişki durumu',
        select_status: 'Durum seç',
        show_hometown: 'Memleketi göster',
        show_age: 'Yaşı göster',
        show_relationship: 'İlişki durumunu göster',
        academic_details: 'Akademik Bilgiler',
        department_label: 'Bölüm / Ana dal',
        select_department: 'Bölüm seç',
        graduation_year_label: 'Mezuniyet yılı / seviye',
        select_year: 'Yıl/seviye seç',
        show_department: 'Bölümü göster',
        show_year: 'Sınıf/yılı göster',
        show_rank: 'Pioneer sırasını göster',
        success: 'Başarılı',
        profile_updated: 'Profil başarıyla güncellendi!',
        error: 'Hata',
        name_required: 'İsim gerekli',
        upload_failed: 'Yükleme başarısız',
        clear: 'Temizle',
        friend_requests: 'Arkadaş istekleri',
        notifications_label: 'Bildirimler',
        theme: 'Tema',
        privacy_policy: 'Gizlilik Politikası',
        terms_of_use: 'Kullanım Şartları',
        privacy_desc: 'Verilerini nasıl koruyoruz',
        terms_desc: 'Öğrenci topluluğu kuralları',
        logout_label: 'Çıkış yap',
        delete_account_label: 'Hesabı sil',
        no_items_yet: 'Henüz içerik yok',
        score: 'Puan',
        pulse_rules_prefix: 'Pulse Kuralları:',
        listed: 'Listelendi',
        reply: 'Yanıt',
        replies: 'Yanıtlar',
        help_out: 'Yardım et',
        replying_to: 'Yanıtlıyor',
        write_comment_placeholder: 'Yorum yaz…',
        activity_header: 'Etkinlik',
        all_caught_up_activity: 'Hepsi okundu',
        activity_empty_sub: 'Önemli güncellemeleri burada bildireceğiz',
        cancel_request: 'İsteği iptal et',
        send_to_friends: 'Arkadaşlara gönder',
        search_friends: 'Arkadaş ara…',
        sent: 'Gönderildi',
        send: 'Gönder',
        no_friends_found: 'Arkadaş bulunamadı',
        no_messages_yet: 'Henüz mesaj yok',
        you_shared_post: 'Bu gönderiyi paylaştın',
        someone_shared_post: '{{name}} bu gönderiyi paylaştı',
        video_label: 'Video',
        photo_label: 'Foto',
        user_fallback: 'Kullanıcı',
        group_fallback: 'Grup',
        conversation_options: 'Sohbet Seçenekleri',
        clear_history: 'Geçmişi Temizle',
        private_label: 'GİZLİ',
        join_required_title: 'Katılım gerekli',
        join_required_body: 'Bu içeriği görmek için üye olmalısın.',
        request_sent_title: 'İstek gönderildi',
        request_sent_body: 'Bir yönetici isteğini inceleyecek.',
        leave_community_title: 'Topluluktan ayrıl',
        leave_community_body: 'Bu topluluktan ayrılmak istiyor musun?',
        retract_request_title: 'İsteği geri çek',
        retract_request_body: 'Katılma isteğini geri çekmek istiyor musun?',
        members_only: 'Sadece üyeler',
        join_to_chat: 'Sohbet için katıl',
        enter_chat_room: 'Sohbete gir',
        post_something: 'Bir şey paylaş',
        admin_creator: 'KURUCUSU',
        students_label: 'Öğrenci',
        manage: 'Yönet',
        locked_body: 'Akışı görmek için bu topluluğa katıl. İçerik gizlidir.',
        just_now: 'Hemen şimdi',
        minute_ago: '{{count}} dk önce',
        hour_ago: '{{count}} sa önce',
        day_ago: '{{count}} gün önce',
        yesterday: 'Dün',
    },
    ka: {
        welcome: 'მოგესალმებით',
        login_subtitle: 'შედით სისტემაში თქვენს კამპუსურ ქსელზე წვდომისთვის.',
        email: 'ელ-ფოსტა',
        password: 'პაროლი',
        forgot_password: 'დაგავიწყდათ პაროლი?',
        login: 'შესვლა',
        no_account: 'არ გაქვთ ანგარიში? ',
        apply_access: 'მოითხოვეთ წვდომა',
        create_account: 'ანგარიშის შექმნა',
        register_subtitle: 'შეუერთდით თქვენს კამპუსურ საზოგადოებას.',
        full_name: 'სრული სახელი',
        already_account: 'უკვე გაქვთ ანგარიში? ',
        login_now: 'შესვლა',
        home: 'მთავარი',
        profile: 'პროფილი',
        notifications: 'შეტყობინებები',
        friends: 'მეგობრები',
        settings: 'პარამეტრები',
        logout: 'გასვლა',
        delete_account: 'ანგარიშის წაშლა',
        posts: 'პოსტები',
        events: 'ღონისძიებები',
        polls: 'გამოკითხვები',
        listings: 'განცხადებები',
        search: 'ძებნა',
        connect: 'დაკავშირება',
        message: 'შეტყობინება',
        edit_profile: 'პროფილის რედაქტირება',
        share_profile: 'პროფილის გაზიარება',
        complete_profile: 'შეავსეთ პროფილი გამოსაჩენად!',
        bio_placeholder: 'დაამატეთ ბიოგრაფია თქვენს შესახებ',
        campus_pioneer: 'კამპუსის პიონერის რანგი',
        loading: 'იტვირთება...',
        feed: 'არხი',
        explore: 'აღმოაჩინე',
        marketplace: 'მარკეტი',
        study: 'სწავლა',
        create: 'შექმნა',
        new_post: 'ახალი პოსტი',
        share_with_campus: 'გაუზიარე კამპუსს',
        new_event: 'ახალი ღონისძიება',
        organize_activities: 'დაგეგმე აქტივობები',
        sell_request: 'გაყიდე ან მოითხოვე',
        list_on_market: 'დაამატე მარკეტში',
        ask_question: 'კითხვის დასმა',
        get_homework_help: 'დახმარება დავალებაში',
        community_hub: 'საზოგადოება',
        search_communities_placeholder: 'მოძებნე თემები...',
        search_students_placeholder: 'სახელით ან დეპარტამენტით',
        communities_tab: 'თემები',
        students_tab: 'სტუდენტები',
        members_count: 'წევრი',
        friends_label: 'მეგობრები',
        requested_label: 'მოთხოვნილია',
        add_friend_label: 'დამატება',
        discover_communities: 'აღმოაჩინე და შეუერთდი',
        start_new_community: 'ახალი თემის შექმნა',
        no_communities_yet: 'თემები არ არის',
        be_the_first: 'იყავი პირველი!',
        no_students_found: 'სტუდენტები ვერ მოიძებნა',
        try_different_search: 'სცადე სხვა სიტყვა',
        all_listings: 'ყველა განცხადება',
        for_sale: 'იყიდება',
        requests_tab: 'მოთხოვნები',
        items_count: 'ნივთი',
        all_communities: 'ყველა თემი',
        filter_by_community: 'გაფილტრე თემით',
        request_badge: 'მოთხოვნა',
        free_badge: 'უფასო',
        new_badge: 'ახალი',
        looking_for: 'ეძებს',
        untitled_item: 'უსახელო ნივთი',
        no_requests_yet: 'მოთხოვნები არ არის',
        no_items_for_sale: 'განცხადებები არ არის',
        nothing_here_yet: 'აქ არაფერია',
        be_the_first_to_request: 'იყავი პირველი ვინც მოითხოვს!',
        be_the_first_to_list: 'იყავი პირველი ვინც დადებს!',
        be_the_first_to_both: 'იყავი პირველი ვინც დადებს!',
        request_an_item: 'ითხოვე ნივთი',
        sell_an_item: 'გაყიდე ნივთი',
        create_a_listing: 'დადე განცხადება',
        all_subjects: 'ყველა',
        no_questions_in: 'კითხვები არ არის:',
        be_the_first_to_ask: 'იყავი პირველი ვინც იკითხავს!',
        search_messages_placeholder: 'მოძებნე შეტყობინებები...',
        no_conversations: 'საუბრები არ არის',
        start_chatting_sub: 'დაიწყე მიმოწერა წევრებთან',
        profile_not_found: 'პროფილი ვერ მოიძებნა',
        user_blocked: 'დაბლოკილია',
        profile_unavailable: 'პროფილი მიუწვდომელია',
        block_desc_me: 'თქვენ დაბლოკეთ ეს მომხმარებელი.',
        block_desc_other: 'თქვენ ვერ ხედავთ ამ მომხმარებელს.',
        unblock_label: 'განბლოკვა',
        connect_label: 'დამატება',
        message_label: 'მიწერა',
        share_profile_label: 'გაზიარება',
        no_content_yet: 'კონტენტი არ არის',
        campus_rank_label: 'კამპუსის პიონერის რანგი',
        score_label: 'ქულა',
        post_tab: 'პოსტები',
        event_tab: 'ღონისძიებები',
        poll_tab: 'გამოკითხვები',
        market_tab: 'მარკეტი',
        math: 'მათემატიკა',
        science: 'მეცნიერება',
        english: 'ინგლისური',
        history: 'ისტორია',
        physics: 'ფიზიკა',
        cs: 'კომპ. მეცნიერება',
        business: 'ბიზნესი',
        arts: 'ხელოვნება',
        other: 'სხვა',
        new_community_header: 'ახალი თემი',
        messages_header: 'შეტყობინებები',
        chat_header: 'ჩატი',
        study_discussion_header: 'სწავლის განხილვა',
        ask_for_help_header: 'ითხოვე დახმარება',
        schedule_event_header: 'დაგეგმე ღონისძიება',
        share_pov_header: 'გააზიარე POV',
        language: 'ენა',
        lang_en: 'ინგლისური',
        lang_tr: 'თურქული',
        lang_ka: 'ქართული',
        books: 'წიგნები',
        clothes: 'ტანსაცმელი',
        accessories: 'აქსესუარები',
        feed_tab: 'არხი',
        events_tab: 'ღონისძიებები',
        market_tab_label: 'მარკეტი',
        list_view: 'სია',
        calendar_view: 'კალენდარი',
        community_not_found: 'თემი ვერ მოიძებნა',
        private_community_title: 'დახურული თემი',
        private_community_body: 'თემის ყურებისთვის შეუერთდი. კონტენტი დაცულია.',
        request_to_join: 'გაგზავნე მოთხოვნა',
        cancel_request: 'მოთხოვნის გაუქმება',
        empty_events: 'ღონისძიებები არ არის.',
        empty_market: 'მარკეტი ცარიელია.',
        empty_feed: 'პირველი გააზიარე რამე!',
        enter_chat_room: 'ჩატში შესვლა',
        members_only: 'მხოლოდ წევრები',
        join_to_chat: 'ჩატისთვის შეერთდი',
        post_something: 'რაღაც გამოაქვეყნე',
        member_status_member: 'წევრი',
        member_status_pending: 'მოთხოვნა გაგზავნილია',
        member_status_request: 'მოთხოვნა',
        member_status_join: 'შეუერთდი თემს',
        admin_creator: 'ადმინისტრატორი',
        study_hub: 'სასწავლო სივრცე',
        private_label: 'დახურული',
        students_label: 'სტუდენტი',
        manage: 'მართვა',
        join_required_title: 'საჭიროა შეერთება',
        join_required_body: 'ჩატში შესასვლელად უნდა იყო წევრი.',
        chat_initializing_title: 'ჩატი იტვირთება',
        chat_initializing_body: 'ჩატის ოთახი სინქრონიზდება. სცადე რამდენიმე წამში.',
        retract_request_title: 'მოთხოვნის გაუქმება',
        retract_request_body: 'დარწმუნებული ხარ, რომ გინდა გააუქმო თხოვნა?',
        leave_community_title: 'თემიდან გასვლა',
        leave_community_body: 'დარწმუნებული ხარ, რომ გინდა დატოვო თემი?',
        request_sent_title: 'მოთხოვნა გაგზავნილია',
        request_sent_body: 'ეს თემი დახურულია. ადმინი განიხილავს.',
        pulse_title: 'Pulse',
        pulse_rules_title: 'Pulse წესები',
        pulse_rules_body: 'არავითარი ბულინგი, სახელები და შევიწროება. დაიცავი კამპუსი.',
        pulse_empty_title: 'Pulse ცარიელია',
        pulse_empty_sub: 'პირველი თქვი შენი აზრი ანონიმურად.',
        pulse_empty_cta: 'დაამატე პოსტი',
        save: 'შენახვა',
        change_profile_picture: 'პროფილის სურათის შეცვლა',
        display_name: 'სახელი',
        username_label: 'მომხმარებელი',
        personal_details: 'პირადი დეტალები (არჩევითი)',
        hometown: 'ქალაქი',
        age: 'ასაკი',
        relationship_status: 'ურთიერთობის სტატუსი',
        select_status: 'აირჩიე სტატუსი',
        show_hometown: 'ქალაქის ჩვენება',
        show_age: 'ასაკის ჩვენება',
        show_relationship: 'სტატუსის ჩვენება',
        academic_details: 'აკადემიური დეტალები',
        department_label: 'ფაკულტეტი / მიმართულება',
        select_department: 'აირჩიე მიმართულება',
        graduation_year_label: 'დამთავრების წელი / დონე',
        select_year: 'აირჩიე წელი/დონე',
        show_department: 'ფაკულტეტის ჩვენება',
        show_year: 'დონის ჩვენება',
        show_rank: 'რანგის ჩვენება',
        success: 'წარმატება',
        profile_updated: 'პროფილი განახლდა!',
        error: 'შეცდომა',
        name_required: 'სახელი საჭიროა',
        upload_failed: 'ატვირთვა ვერ მოხერხდა',
        clear: 'გასუფთავება',
        friend_requests: 'მეგობრობის მოთხოვნები',
        notifications_label: 'შეტყობინებები',
        theme: 'თემა',
        privacy_policy: 'კონფიდენციალურობა',
        terms_of_use: 'გამოყენების პირობები',
        privacy_desc: 'როგორ ვიცავთ მონაცემებს',
        terms_desc: 'ჩვენი საზოგადოების წესები',
        logout_label: 'გასვლა',
        delete_account_label: 'ანგარიშის წაშლა',
        no_items_yet: 'ჯერ არაფერია',
        score: 'ქულა',
        pulse_rules_prefix: 'Pulse წესები:',
        listed: 'დალისტდა',
        just_now: 'ახლახან',
        minute_ago: '{{count}}წთ წინ',
        hour_ago: '{{count}}სთ წინ',
        day_ago: '{{count}} დღე წინ',
        yesterday: 'გუშინ',
        reply: 'პასუხი',
        replies: 'პასუხები',
        help_out: 'დაეხმარე',
        replying_to: 'პასუხობ',
        write_comment_placeholder: 'დაწერე კომენტარი…',
        activity_header: 'აქტივობა',
        all_caught_up_activity: 'ყველა წაკითხულია',
        activity_empty_sub: 'მნიშვნელოვან ამბებს აქ შეგატყობინებთ',
        cancel_request: 'მოთხოვნის გაუქმება',
        send_to_friends: 'გაგზავნა მეგობრებთან',
        search_friends: 'მეგობრების ძებნა…',
        sent: 'გაგზავნილია',
        send: 'გაგზავნა',
        no_friends_found: 'მეგობრები ვერ მოიძებნა',
        no_messages_yet: 'შეტყობინებები ჯერ არ არის',
        you_shared_post: 'შენ გააზიარე ეს პოსტი',
        someone_shared_post: '{{name}}-მა გააზიარა ეს პოსტი',
        video_label: 'ვიდეო',
        photo_label: 'ფოტო',
        user_fallback: 'მომხმარებელი',
        group_fallback: 'ჯგუფი',
        conversation_options: 'საუბრის პარამეტრები',
        clear_history: 'ისტორიის გასუფთავება',
        private_label: 'დახურული',
        join_required_title: 'საჭიროა შეერთება',
        join_required_body: 'შინაარსის სანახავად შეუერთდი თემს.',
        request_sent_title: 'მოთხოვნა გაგზავნილია',
        request_sent_body: 'ადმინი განიხილავს თქვენს თხოვნას.',
        leave_community_title: 'თემიდან გასვლა',
        leave_community_body: 'დარწმუნებული ხარ, რომ გინდა დატოვო თემი?',
        retract_request_title: 'მოთხოვნის გაუქმება',
        retract_request_body: 'დარწმუნებული ხარ, რომ გინდა გააუქმო მოთხოვნა?',
        members_only: 'მხოლოდ წევრები',
        join_to_chat: 'ჩატისთვის შეერთდი',
        enter_chat_room: 'ჩატში შესვლა',
        post_something: 'რაღაც გამოაქვეყნე',
        admin_creator: 'ადმინისტრატორი',
        students_label: 'სტუდენტი',
        manage: 'მართვა',
        locked_body: 'შეუერთდი თემს, რომ ნახო კონტენტი. კონფიდენციალურობისთვის დაფარულია.',
    }
};

export type TranslationKey = keyof typeof translations['en'];

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof typeof translations['en']) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const loadLanguage = async () => {
            const saved = await AsyncStorage.getItem('user_language');
            if (saved && (saved === 'en' || saved === 'tr' || saved === 'ka')) {
                setLanguageState(saved as Language);
            }
        };
        loadLanguage();
    }, []);

    const setLanguage = async (lang: Language) => {
        setLanguageState(lang);
        await AsyncStorage.setItem('user_language', lang);
    };

    const t = (key: keyof typeof translations['en']): string => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
